module OpenGL

require("GetC")
import GetC.@get_c_fun

#Autogenerated, hopefully stays that way!
gl = dlopen("libGL")

#TODO so many things to export...

typealias GLenum Uint32
export GLenum
typealias GLboolean Uint8
export GLboolean
typealias GLbitfield Uint32
export GLbitfield
typealias GLvoid Void
export GLvoid
typealias GLbyte Uint8
export GLbyte
typealias GLshort Int16
export GLshort
typealias GLint Int32
export GLint
typealias GLubyte Uint8
export GLubyte
typealias GLushort Uint16
export GLushort
typealias GLuint Uint32
export GLuint
typealias GLsizei Int32
export GLsizei
typealias GLfloat Float32
export GLfloat
typealias GLclampf Float32
export GLclampf
typealias GLdouble Float64
export GLdouble
typealias GLclampd Float64
export GLclampd
@get_c_fun gl glclearindex glClearIndex(c::GLfloat)::Void
export glclearindex
@get_c_fun gl glclearcolor glClearColor(red::GLclampf,green::GLclampf,blue::GLclampf,alpha::GLclampf)::Void
export glclearcolor
@get_c_fun gl glclear glClear(mask::GLbitfield)::Void
export glclear
@get_c_fun gl glindexmask glIndexMask(mask::GLuint)::Void
export glindexmask
@get_c_fun gl glcolormask glColorMask(red::GLboolean,green::GLboolean,blue::GLboolean,alpha::GLboolean)::Void
export glcolormask
@get_c_fun gl glalphafunc glAlphaFunc(func::GLenum,ref::GLclampf)::Void
export glalphafunc
@get_c_fun gl glblendfunc glBlendFunc(sfactor::GLenum,dfactor::GLenum)::Void
export glblendfunc
@get_c_fun gl gllogicop glLogicOp(opcode::GLenum)::Void
export gllogicop
@get_c_fun gl glcullface glCullFace(mode::GLenum)::Void
export glcullface
@get_c_fun gl glfrontface glFrontFace(mode::GLenum)::Void
export glfrontface
@get_c_fun gl glpointsize glPointSize(size::GLfloat)::Void
export glpointsize
@get_c_fun gl gllinewidth glLineWidth(width::GLfloat)::Void
export gllinewidth
@get_c_fun gl gllinestipple glLineStipple(factor::GLint,pattern::GLushort)::Void
export gllinestipple
@get_c_fun gl glpolygonmode glPolygonMode(face::GLenum,mode::GLenum)::Void
export glpolygonmode
@get_c_fun gl glpolygonoffset glPolygonOffset(factor::GLfloat,units::GLfloat)::Void
export glpolygonoffset
@get_c_fun gl glpolygonstipple glPolygonStipple(mask::Ptr)::Void
export glpolygonstipple
@get_c_fun gl glgetpolygonstipple glGetPolygonStipple(mask::Ptr)::Void
export glgetpolygonstipple
@get_c_fun gl gledgeflag glEdgeFlag(flag::GLboolean)::Void
export gledgeflag
@get_c_fun gl gledgeflagv glEdgeFlagv(flag::Ptr)::Void
export gledgeflagv
@get_c_fun gl glscissor glScissor(x::GLint,y::GLint,width::GLsizei,height::GLsizei)::Void
export glscissor
@get_c_fun gl glclipplane glClipPlane(plane::GLenum,equation::Ptr)::Void
export glclipplane
@get_c_fun gl glgetclipplane glGetClipPlane(plane::GLenum,equation::Ptr)::Void
export glgetclipplane
@get_c_fun gl gldrawbuffer glDrawBuffer(mode::GLenum)::Void
export gldrawbuffer
@get_c_fun gl glreadbuffer glReadBuffer(mode::GLenum)::Void
export glreadbuffer
@get_c_fun gl glenable glEnable(cap::GLenum)::Void
export glenable
@get_c_fun gl gldisable glDisable(cap::GLenum)::Void
export gldisable
@get_c_fun gl glisenabled glIsEnabled(cap::GLenum)::GLboolean
export glisenabled
@get_c_fun gl glenableclientstate glEnableClientState(cap::GLenum)::Void
export glenableclientstate
@get_c_fun gl gldisableclientstate glDisableClientState(cap::GLenum)::Void
export gldisableclientstate
@get_c_fun gl glgetbooleanv glGetBooleanv(pname::GLenum,params::Ptr)::Void
export glgetbooleanv
@get_c_fun gl glgetdoublev glGetDoublev(pname::GLenum,params::Ptr)::Void
export glgetdoublev
@get_c_fun gl glgetfloatv glGetFloatv(pname::GLenum,params::Ptr)::Void
export glgetfloatv
@get_c_fun gl glgetintegerv glGetIntegerv(pname::GLenum,params::Ptr)::Void
export glgetintegerv
@get_c_fun gl glpushattrib glPushAttrib(mask::GLbitfield)::Void
export glpushattrib
@get_c_fun gl glpopattrib glPopAttrib()::Void
export glpopattrib
@get_c_fun gl glpushclientattrib glPushClientAttrib(mask::GLbitfield)::Void
export glpushclientattrib
@get_c_fun gl glpopclientattrib glPopClientAttrib()::Void
export glpopclientattrib
@get_c_fun gl glrendermode glRenderMode(mode::GLenum)::GLint
export glrendermode
@get_c_fun gl glgeterror glGetError()::GLenum
export glgeterror
@get_c_fun gl glgetstring glGetString(name::GLenum)::GLubyte
export glgetstring
@get_c_fun gl glfinish glFinish()::Void
export glfinish
@get_c_fun gl glflush glFlush()::Void
export glflush
@get_c_fun gl glhint glHint(target::GLenum,mode::GLenum)::Void
export glhint
@get_c_fun gl glcleardepth glClearDepth(depth::GLclampd)::Void
export glcleardepth
@get_c_fun gl gldepthfunc glDepthFunc(func::GLenum)::Void
export gldepthfunc
@get_c_fun gl gldepthmask glDepthMask(flag::GLboolean)::Void
export gldepthmask
@get_c_fun gl gldepthrange glDepthRange(near_val::GLclampd,far_val::GLclampd)::Void
export gldepthrange
@get_c_fun gl glclearaccum glClearAccum(red::GLfloat,green::GLfloat,blue::GLfloat,alpha::GLfloat)::Void
export glclearaccum
@get_c_fun gl glaccum glAccum(op::GLenum,value::GLfloat)::Void
export glaccum
@get_c_fun gl glmatrixmode glMatrixMode(mode::GLenum)::Void
export glmatrixmode
@get_c_fun gl glortho glOrtho(left::GLdouble,right::GLdouble,bottom::GLdouble,top::GLdouble,near_val::GLdouble,far_val::GLdouble)::Void
export glortho
@get_c_fun gl glfrustum glFrustum(left::GLdouble,right::GLdouble,bottom::GLdouble,top::GLdouble,near_val::GLdouble,far_val::GLdouble)::Void
export glfrustum
@get_c_fun gl glviewport glViewport(x::GLint,y::GLint,width::GLsizei,height::GLsizei)::Void
export glviewport
@get_c_fun gl glpushmatrix glPushMatrix()::Void
export glpushmatrix
@get_c_fun gl glpopmatrix glPopMatrix()::Void
export glpopmatrix
@get_c_fun gl glloadidentity glLoadIdentity()::Void
export glloadidentity
@get_c_fun gl glloadmatrixd glLoadMatrixd(m::Ptr)::Void
export glloadmatrixd
@get_c_fun gl glloadmatrixf glLoadMatrixf(m::Ptr)::Void
export glloadmatrixf
@get_c_fun gl glmultmatrixd glMultMatrixd(m::Ptr)::Void
export glmultmatrixd
@get_c_fun gl glmultmatrixf glMultMatrixf(m::Ptr)::Void
export glmultmatrixf
@get_c_fun gl glrotated glRotated(angle::GLdouble,x::GLdouble,y::GLdouble,z::GLdouble)::Void
export glrotated
@get_c_fun gl glrotatef glRotatef(angle::GLfloat,x::GLfloat,y::GLfloat,z::GLfloat)::Void
export glrotatef
@get_c_fun gl glscaled glScaled(x::GLdouble,y::GLdouble,z::GLdouble)::Void
export glscaled
@get_c_fun gl glscalef glScalef(x::GLfloat,y::GLfloat,z::GLfloat)::Void
export glscalef
@get_c_fun gl gltranslated glTranslated(x::GLdouble,y::GLdouble,z::GLdouble)::Void
export gltranslated
@get_c_fun gl gltranslatef glTranslatef(x::GLfloat,y::GLfloat,z::GLfloat)::Void
export gltranslatef
@get_c_fun gl glislist glIsList(list::GLuint)::GLboolean
export glislist
@get_c_fun gl gldeletelists glDeleteLists(list::GLuint,range::GLsizei)::Void
export gldeletelists
@get_c_fun gl glgenlists glGenLists(range::GLsizei)::GLuint
export glgenlists
@get_c_fun gl glnewlist glNewList(list::GLuint,mode::GLenum)::Void
export glnewlist
@get_c_fun gl glendlist glEndList()::Void
export glendlist
@get_c_fun gl glcalllist glCallList(list::GLuint)::Void
export glcalllist
@get_c_fun gl glcalllists glCallLists(n::GLsizei,_type::GLenum,lists::Ptr)::Void
export glcalllists
@get_c_fun gl gllistbase glListBase(base::GLuint)::Void
export gllistbase
@get_c_fun gl glbegin glBegin(mode::GLenum)::Void
export glbegin
@get_c_fun gl glend glEnd()::Void
export glend
@get_c_fun gl glvertex2d glVertex2d(x::GLdouble,y::GLdouble)::Void
export glvertex2d
@get_c_fun gl glvertex2f glVertex2f(x::GLfloat,y::GLfloat)::Void
export glvertex2f
@get_c_fun gl glvertex2i glVertex2i(x::GLint,y::GLint)::Void
export glvertex2i
@get_c_fun gl glvertex2s glVertex2s(x::GLshort,y::GLshort)::Void
export glvertex2s
@get_c_fun gl glvertex3d glVertex3d(x::GLdouble,y::GLdouble,z::GLdouble)::Void
export glvertex3d
@get_c_fun gl glvertex3f glVertex3f(x::GLfloat,y::GLfloat,z::GLfloat)::Void
export glvertex3f
@get_c_fun gl glvertex3i glVertex3i(x::GLint,y::GLint,z::GLint)::Void
export glvertex3i
@get_c_fun gl glvertex3s glVertex3s(x::GLshort,y::GLshort,z::GLshort)::Void
export glvertex3s
@get_c_fun gl glvertex4d glVertex4d(x::GLdouble,y::GLdouble,z::GLdouble,w::GLdouble)::Void
export glvertex4d
@get_c_fun gl glvertex4f glVertex4f(x::GLfloat,y::GLfloat,z::GLfloat,w::GLfloat)::Void
export glvertex4f
@get_c_fun gl glvertex4i glVertex4i(x::GLint,y::GLint,z::GLint,w::GLint)::Void
export glvertex4i
@get_c_fun gl glvertex4s glVertex4s(x::GLshort,y::GLshort,z::GLshort,w::GLshort)::Void
export glvertex4s
@get_c_fun gl glvertex2dv glVertex2dv(v::Ptr)::Void
export glvertex2dv
@get_c_fun gl glvertex2fv glVertex2fv(v::Ptr)::Void
export glvertex2fv
@get_c_fun gl glvertex2iv glVertex2iv(v::Ptr)::Void
export glvertex2iv
@get_c_fun gl glvertex2sv glVertex2sv(v::Ptr)::Void
export glvertex2sv
@get_c_fun gl glvertex3dv glVertex3dv(v::Ptr)::Void
export glvertex3dv
@get_c_fun gl glvertex3fv glVertex3fv(v::Ptr)::Void
export glvertex3fv
@get_c_fun gl glvertex3iv glVertex3iv(v::Ptr)::Void
export glvertex3iv
@get_c_fun gl glvertex3sv glVertex3sv(v::Ptr)::Void
export glvertex3sv
@get_c_fun gl glvertex4dv glVertex4dv(v::Ptr)::Void
export glvertex4dv
@get_c_fun gl glvertex4fv glVertex4fv(v::Ptr)::Void
export glvertex4fv
@get_c_fun gl glvertex4iv glVertex4iv(v::Ptr)::Void
export glvertex4iv
@get_c_fun gl glvertex4sv glVertex4sv(v::Ptr)::Void
export glvertex4sv
@get_c_fun gl glnormal3b glNormal3b(nx::GLbyte,ny::GLbyte,nz::GLbyte)::Void
export glnormal3b
@get_c_fun gl glnormal3d glNormal3d(nx::GLdouble,ny::GLdouble,nz::GLdouble)::Void
export glnormal3d
@get_c_fun gl glnormal3f glNormal3f(nx::GLfloat,ny::GLfloat,nz::GLfloat)::Void
export glnormal3f
@get_c_fun gl glnormal3i glNormal3i(nx::GLint,ny::GLint,nz::GLint)::Void
export glnormal3i
@get_c_fun gl glnormal3s glNormal3s(nx::GLshort,ny::GLshort,nz::GLshort)::Void
export glnormal3s
@get_c_fun gl glnormal3bv glNormal3bv(v::Ptr)::Void
export glnormal3bv
@get_c_fun gl glnormal3dv glNormal3dv(v::Ptr)::Void
export glnormal3dv
@get_c_fun gl glnormal3fv glNormal3fv(v::Ptr)::Void
export glnormal3fv
@get_c_fun gl glnormal3iv glNormal3iv(v::Ptr)::Void
export glnormal3iv
@get_c_fun gl glnormal3sv glNormal3sv(v::Ptr)::Void
export glnormal3sv
@get_c_fun gl glindexd glIndexd(c::GLdouble)::Void
export glindexd
@get_c_fun gl glindexf glIndexf(c::GLfloat)::Void
export glindexf
@get_c_fun gl glindexi glIndexi(c::GLint)::Void
export glindexi
@get_c_fun gl glindexs glIndexs(c::GLshort)::Void
export glindexs
@get_c_fun gl glindexub glIndexub(c::GLubyte)::Void
export glindexub
@get_c_fun gl glindexdv glIndexdv(c::Ptr)::Void
export glindexdv
@get_c_fun gl glindexfv glIndexfv(c::Ptr)::Void
export glindexfv
@get_c_fun gl glindexiv glIndexiv(c::Ptr)::Void
export glindexiv
@get_c_fun gl glindexsv glIndexsv(c::Ptr)::Void
export glindexsv
@get_c_fun gl glindexubv glIndexubv(c::Ptr)::Void
export glindexubv
@get_c_fun gl glcolor3b glColor3b(red::GLbyte,green::GLbyte,blue::GLbyte)::Void
export glcolor3b
@get_c_fun gl glcolor3d glColor3d(red::GLdouble,green::GLdouble,blue::GLdouble)::Void
export glcolor3d
@get_c_fun gl glcolor3f glColor3f(red::GLfloat,green::GLfloat,blue::GLfloat)::Void
export glcolor3f
@get_c_fun gl glcolor3i glColor3i(red::GLint,green::GLint,blue::GLint)::Void
export glcolor3i
@get_c_fun gl glcolor3s glColor3s(red::GLshort,green::GLshort,blue::GLshort)::Void
export glcolor3s
@get_c_fun gl glcolor3ub glColor3ub(red::GLubyte,green::GLubyte,blue::GLubyte)::Void
export glcolor3ub
@get_c_fun gl glcolor3ui glColor3ui(red::GLuint,green::GLuint,blue::GLuint)::Void
export glcolor3ui
@get_c_fun gl glcolor3us glColor3us(red::GLushort,green::GLushort,blue::GLushort)::Void
export glcolor3us
@get_c_fun gl glcolor4b glColor4b(red::GLbyte,green::GLbyte,blue::GLbyte,alpha::GLbyte)::Void
export glcolor4b
@get_c_fun gl glcolor4d glColor4d(red::GLdouble,green::GLdouble,blue::GLdouble,alpha::GLdouble)::Void
export glcolor4d
@get_c_fun gl glcolor4f glColor4f(red::GLfloat,green::GLfloat,blue::GLfloat,alpha::GLfloat)::Void
export glcolor4f
@get_c_fun gl glcolor4i glColor4i(red::GLint,green::GLint,blue::GLint,alpha::GLint)::Void
export glcolor4i
@get_c_fun gl glcolor4s glColor4s(red::GLshort,green::GLshort,blue::GLshort,alpha::GLshort)::Void
export glcolor4s
@get_c_fun gl glcolor4ub glColor4ub(red::GLubyte,green::GLubyte,blue::GLubyte,alpha::GLubyte)::Void
export glcolor4ub
@get_c_fun gl glcolor4ui glColor4ui(red::GLuint,green::GLuint,blue::GLuint,alpha::GLuint)::Void
export glcolor4ui
@get_c_fun gl glcolor4us glColor4us(red::GLushort,green::GLushort,blue::GLushort,alpha::GLushort)::Void
export glcolor4us
@get_c_fun gl glcolor3bv glColor3bv(v::Ptr)::Void
export glcolor3bv
@get_c_fun gl glcolor3dv glColor3dv(v::Ptr)::Void
export glcolor3dv
@get_c_fun gl glcolor3fv glColor3fv(v::Ptr)::Void
export glcolor3fv
@get_c_fun gl glcolor3iv glColor3iv(v::Ptr)::Void
export glcolor3iv
@get_c_fun gl glcolor3sv glColor3sv(v::Ptr)::Void
export glcolor3sv
@get_c_fun gl glcolor3ubv glColor3ubv(v::Ptr)::Void
export glcolor3ubv
@get_c_fun gl glcolor3uiv glColor3uiv(v::Ptr)::Void
export glcolor3uiv
@get_c_fun gl glcolor3usv glColor3usv(v::Ptr)::Void
export glcolor3usv
@get_c_fun gl glcolor4bv glColor4bv(v::Ptr)::Void
export glcolor4bv
@get_c_fun gl glcolor4dv glColor4dv(v::Ptr)::Void
export glcolor4dv
@get_c_fun gl glcolor4fv glColor4fv(v::Ptr)::Void
export glcolor4fv
@get_c_fun gl glcolor4iv glColor4iv(v::Ptr)::Void
export glcolor4iv
@get_c_fun gl glcolor4sv glColor4sv(v::Ptr)::Void
export glcolor4sv
@get_c_fun gl glcolor4ubv glColor4ubv(v::Ptr)::Void
export glcolor4ubv
@get_c_fun gl glcolor4uiv glColor4uiv(v::Ptr)::Void
export glcolor4uiv
@get_c_fun gl glcolor4usv glColor4usv(v::Ptr)::Void
export glcolor4usv
@get_c_fun gl gltexcoord1d glTexCoord1d(s::GLdouble)::Void
export gltexcoord1d
@get_c_fun gl gltexcoord1f glTexCoord1f(s::GLfloat)::Void
export gltexcoord1f
@get_c_fun gl gltexcoord1i glTexCoord1i(s::GLint)::Void
export gltexcoord1i
@get_c_fun gl gltexcoord1s glTexCoord1s(s::GLshort)::Void
export gltexcoord1s
@get_c_fun gl gltexcoord2d glTexCoord2d(s::GLdouble,t::GLdouble)::Void
export gltexcoord2d
@get_c_fun gl gltexcoord2f glTexCoord2f(s::GLfloat,t::GLfloat)::Void
export gltexcoord2f
@get_c_fun gl gltexcoord2i glTexCoord2i(s::GLint,t::GLint)::Void
export gltexcoord2i
@get_c_fun gl gltexcoord2s glTexCoord2s(s::GLshort,t::GLshort)::Void
export gltexcoord2s
@get_c_fun gl gltexcoord3d glTexCoord3d(s::GLdouble,t::GLdouble,r::GLdouble)::Void
export gltexcoord3d
@get_c_fun gl gltexcoord3f glTexCoord3f(s::GLfloat,t::GLfloat,r::GLfloat)::Void
export gltexcoord3f
@get_c_fun gl gltexcoord3i glTexCoord3i(s::GLint,t::GLint,r::GLint)::Void
export gltexcoord3i
@get_c_fun gl gltexcoord3s glTexCoord3s(s::GLshort,t::GLshort,r::GLshort)::Void
export gltexcoord3s
@get_c_fun gl gltexcoord4d glTexCoord4d(s::GLdouble,t::GLdouble,r::GLdouble,q::GLdouble)::Void
export gltexcoord4d
@get_c_fun gl gltexcoord4f glTexCoord4f(s::GLfloat,t::GLfloat,r::GLfloat,q::GLfloat)::Void
export gltexcoord4f
@get_c_fun gl gltexcoord4i glTexCoord4i(s::GLint,t::GLint,r::GLint,q::GLint)::Void
export gltexcoord4i
@get_c_fun gl gltexcoord4s glTexCoord4s(s::GLshort,t::GLshort,r::GLshort,q::GLshort)::Void
export gltexcoord4s
@get_c_fun gl gltexcoord1dv glTexCoord1dv(v::Ptr)::Void
export gltexcoord1dv
@get_c_fun gl gltexcoord1fv glTexCoord1fv(v::Ptr)::Void
export gltexcoord1fv
@get_c_fun gl gltexcoord1iv glTexCoord1iv(v::Ptr)::Void
export gltexcoord1iv
@get_c_fun gl gltexcoord1sv glTexCoord1sv(v::Ptr)::Void
export gltexcoord1sv
@get_c_fun gl gltexcoord2dv glTexCoord2dv(v::Ptr)::Void
export gltexcoord2dv
@get_c_fun gl gltexcoord2fv glTexCoord2fv(v::Ptr)::Void
export gltexcoord2fv
@get_c_fun gl gltexcoord2iv glTexCoord2iv(v::Ptr)::Void
export gltexcoord2iv
@get_c_fun gl gltexcoord2sv glTexCoord2sv(v::Ptr)::Void
export gltexcoord2sv
@get_c_fun gl gltexcoord3dv glTexCoord3dv(v::Ptr)::Void
export gltexcoord3dv
@get_c_fun gl gltexcoord3fv glTexCoord3fv(v::Ptr)::Void
export gltexcoord3fv
@get_c_fun gl gltexcoord3iv glTexCoord3iv(v::Ptr)::Void
export gltexcoord3iv
@get_c_fun gl gltexcoord3sv glTexCoord3sv(v::Ptr)::Void
export gltexcoord3sv
@get_c_fun gl gltexcoord4dv glTexCoord4dv(v::Ptr)::Void
export gltexcoord4dv
@get_c_fun gl gltexcoord4fv glTexCoord4fv(v::Ptr)::Void
export gltexcoord4fv
@get_c_fun gl gltexcoord4iv glTexCoord4iv(v::Ptr)::Void
export gltexcoord4iv
@get_c_fun gl gltexcoord4sv glTexCoord4sv(v::Ptr)::Void
export gltexcoord4sv
@get_c_fun gl glrasterpos2d glRasterPos2d(x::GLdouble,y::GLdouble)::Void
export glrasterpos2d
@get_c_fun gl glrasterpos2f glRasterPos2f(x::GLfloat,y::GLfloat)::Void
export glrasterpos2f
@get_c_fun gl glrasterpos2i glRasterPos2i(x::GLint,y::GLint)::Void
export glrasterpos2i
@get_c_fun gl glrasterpos2s glRasterPos2s(x::GLshort,y::GLshort)::Void
export glrasterpos2s
@get_c_fun gl glrasterpos3d glRasterPos3d(x::GLdouble,y::GLdouble,z::GLdouble)::Void
export glrasterpos3d
@get_c_fun gl glrasterpos3f glRasterPos3f(x::GLfloat,y::GLfloat,z::GLfloat)::Void
export glrasterpos3f
@get_c_fun gl glrasterpos3i glRasterPos3i(x::GLint,y::GLint,z::GLint)::Void
export glrasterpos3i
@get_c_fun gl glrasterpos3s glRasterPos3s(x::GLshort,y::GLshort,z::GLshort)::Void
export glrasterpos3s
@get_c_fun gl glrasterpos4d glRasterPos4d(x::GLdouble,y::GLdouble,z::GLdouble,w::GLdouble)::Void
export glrasterpos4d
@get_c_fun gl glrasterpos4f glRasterPos4f(x::GLfloat,y::GLfloat,z::GLfloat,w::GLfloat)::Void
export glrasterpos4f
@get_c_fun gl glrasterpos4i glRasterPos4i(x::GLint,y::GLint,z::GLint,w::GLint)::Void
export glrasterpos4i
@get_c_fun gl glrasterpos4s glRasterPos4s(x::GLshort,y::GLshort,z::GLshort,w::GLshort)::Void
export glrasterpos4s
@get_c_fun gl glrasterpos2dv glRasterPos2dv(v::Ptr)::Void
export glrasterpos2dv
@get_c_fun gl glrasterpos2fv glRasterPos2fv(v::Ptr)::Void
export glrasterpos2fv
@get_c_fun gl glrasterpos2iv glRasterPos2iv(v::Ptr)::Void
export glrasterpos2iv
@get_c_fun gl glrasterpos2sv glRasterPos2sv(v::Ptr)::Void
export glrasterpos2sv
@get_c_fun gl glrasterpos3dv glRasterPos3dv(v::Ptr)::Void
export glrasterpos3dv
@get_c_fun gl glrasterpos3fv glRasterPos3fv(v::Ptr)::Void
export glrasterpos3fv
@get_c_fun gl glrasterpos3iv glRasterPos3iv(v::Ptr)::Void
export glrasterpos3iv
@get_c_fun gl glrasterpos3sv glRasterPos3sv(v::Ptr)::Void
export glrasterpos3sv
@get_c_fun gl glrasterpos4dv glRasterPos4dv(v::Ptr)::Void
export glrasterpos4dv
@get_c_fun gl glrasterpos4fv glRasterPos4fv(v::Ptr)::Void
export glrasterpos4fv
@get_c_fun gl glrasterpos4iv glRasterPos4iv(v::Ptr)::Void
export glrasterpos4iv
@get_c_fun gl glrasterpos4sv glRasterPos4sv(v::Ptr)::Void
export glrasterpos4sv
@get_c_fun gl glrectd glRectd(x1::GLdouble,y1::GLdouble,x2::GLdouble,y2::GLdouble)::Void
export glrectd
@get_c_fun gl glrectf glRectf(x1::GLfloat,y1::GLfloat,x2::GLfloat,y2::GLfloat)::Void
export glrectf
@get_c_fun gl glrecti glRecti(x1::GLint,y1::GLint,x2::GLint,y2::GLint)::Void
export glrecti
@get_c_fun gl glrects glRects(x1::GLshort,y1::GLshort,x2::GLshort,y2::GLshort)::Void
export glrects
@get_c_fun gl glrectdv glRectdv(v1::Ptr,v2::Ptr)::Void
export glrectdv
@get_c_fun gl glrectfv glRectfv(v1::Ptr,v2::Ptr)::Void
export glrectfv
@get_c_fun gl glrectiv glRectiv(v1::Ptr,v2::Ptr)::Void
export glrectiv
@get_c_fun gl glrectsv glRectsv(v1::Ptr,v2::Ptr)::Void
export glrectsv
@get_c_fun gl glvertexpointer glVertexPointer(size::GLint,_type::GLenum,stride::GLsizei,ptr::Ptr)::Void
export glvertexpointer
@get_c_fun gl glnormalpointer glNormalPointer(_type::GLenum,stride::GLsizei,ptr::Ptr)::Void
export glnormalpointer
@get_c_fun gl glcolorpointer glColorPointer(size::GLint,_type::GLenum,stride::GLsizei,ptr::Ptr)::Void
export glcolorpointer
@get_c_fun gl glindexpointer glIndexPointer(_type::GLenum,stride::GLsizei,ptr::Ptr)::Void
export glindexpointer
@get_c_fun gl gltexcoordpointer glTexCoordPointer(size::GLint,_type::GLenum,stride::GLsizei,ptr::Ptr)::Void
export gltexcoordpointer
@get_c_fun gl gledgeflagpointer glEdgeFlagPointer(stride::GLsizei,ptr::Ptr)::Void
export gledgeflagpointer
@get_c_fun gl glgetpointerv glGetPointerv(pname::GLenum,params::Ptr)::Void
export glgetpointerv
@get_c_fun gl glarrayelement glArrayElement(i::GLint)::Void
export glarrayelement
@get_c_fun gl gldrawarrays glDrawArrays(mode::GLenum,first::GLint,count::GLsizei)::Void
export gldrawarrays
@get_c_fun gl gldrawelements glDrawElements(mode::GLenum,count::GLsizei,_type::GLenum,indices::Ptr)::Void
export gldrawelements
@get_c_fun gl glinterleavedarrays glInterleavedArrays(format::GLenum,stride::GLsizei,pointer::Ptr)::Void
export glinterleavedarrays
@get_c_fun gl glshademodel glShadeModel(mode::GLenum)::Void
export glshademodel
@get_c_fun gl gllightf glLightf(light::GLenum,pname::GLenum,param::GLfloat)::Void
export gllightf
@get_c_fun gl gllighti glLighti(light::GLenum,pname::GLenum,param::GLint)::Void
export gllighti
@get_c_fun gl gllightfv glLightfv(light::GLenum,pname::GLenum,params::Ptr{Float64})::Void
export gllightfv
@get_c_fun gl gllightiv glLightiv(light::GLenum,pname::GLenum,params::Ptr)::Void
export gllightiv
@get_c_fun gl glgetlightfv glGetLightfv(light::GLenum,pname::GLenum,params::Ptr)::Void
export glgetlightfv
@get_c_fun gl glgetlightiv glGetLightiv(light::GLenum,pname::GLenum,params::Ptr)::Void
export glgetlightiv
@get_c_fun gl gllightmodelf glLightModelf(pname::GLenum,param::GLfloat)::Void
export gllightmodelf
@get_c_fun gl gllightmodeli glLightModeli(pname::GLenum,param::GLint)::Void
export gllightmodeli
@get_c_fun gl gllightmodelfv glLightModelfv(pname::GLenum,params::Ptr)::Void
export gllightmodelfv
@get_c_fun gl gllightmodeliv glLightModeliv(pname::GLenum,params::Ptr)::Void
export gllightmodeliv
@get_c_fun gl glmaterialf glMaterialf(face::GLenum,pname::GLenum,param::GLfloat)::Void
export glmaterialf
@get_c_fun gl glmateriali glMateriali(face::GLenum,pname::GLenum,param::GLint)::Void
export glmateriali
@get_c_fun gl glmaterialfv glMaterialfv(face::GLenum,pname::GLenum,params::Ptr)::Void
export glmaterialfv
@get_c_fun gl glmaterialiv glMaterialiv(face::GLenum,pname::GLenum,params::Ptr)::Void
export glmaterialiv
@get_c_fun gl glgetmaterialfv glGetMaterialfv(face::GLenum,pname::GLenum,params::Ptr)::Void
export glgetmaterialfv
@get_c_fun gl glgetmaterialiv glGetMaterialiv(face::GLenum,pname::GLenum,params::Ptr)::Void
export glgetmaterialiv
@get_c_fun gl glcolormaterial glColorMaterial(face::GLenum,mode::GLenum)::Void
export glcolormaterial
@get_c_fun gl glpixelzoom glPixelZoom(xfactor::GLfloat,yfactor::GLfloat)::Void
export glpixelzoom
@get_c_fun gl glpixelstoref glPixelStoref(pname::GLenum,param::GLfloat)::Void
export glpixelstoref
@get_c_fun gl glpixelstorei glPixelStorei(pname::GLenum,param::GLint)::Void
export glpixelstorei
@get_c_fun gl glpixeltransferf glPixelTransferf(pname::GLenum,param::GLfloat)::Void
export glpixeltransferf
@get_c_fun gl glpixeltransferi glPixelTransferi(pname::GLenum,param::GLint)::Void
export glpixeltransferi
@get_c_fun gl glpixelmapfv glPixelMapfv(map::GLenum,mapsize::GLsizei,values::Ptr)::Void
export glpixelmapfv
@get_c_fun gl glpixelmapuiv glPixelMapuiv(map::GLenum,mapsize::GLsizei,values::Ptr)::Void
export glpixelmapuiv
@get_c_fun gl glpixelmapusv glPixelMapusv(map::GLenum,mapsize::GLsizei,values::Ptr)::Void
export glpixelmapusv
@get_c_fun gl glgetpixelmapfv glGetPixelMapfv(map::GLenum,values::Ptr)::Void
export glgetpixelmapfv
@get_c_fun gl glgetpixelmapuiv glGetPixelMapuiv(map::GLenum,values::Ptr)::Void
export glgetpixelmapuiv
@get_c_fun gl glgetpixelmapusv glGetPixelMapusv(map::GLenum,values::Ptr)::Void
export glgetpixelmapusv
@get_c_fun gl glbitmap glBitmap(width::GLsizei,height::GLsizei,xorig::GLfloat,yorig::GLfloat,xmove::GLfloat,ymove::GLfloat,bitmap::Ptr)::Void
export glbitmap
@get_c_fun gl glreadpixels glReadPixels(x::GLint,y::GLint,width::GLsizei,height::GLsizei,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export glreadpixels
@get_c_fun gl gldrawpixels glDrawPixels(width::GLsizei,height::GLsizei,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export gldrawpixels
@get_c_fun gl glcopypixels glCopyPixels(x::GLint,y::GLint,width::GLsizei,height::GLsizei,_type::GLenum)::Void
export glcopypixels
@get_c_fun gl glstencilfunc glStencilFunc(func::GLenum,ref::GLint,mask::GLuint)::Void
export glstencilfunc
@get_c_fun gl glstencilmask glStencilMask(mask::GLuint)::Void
export glstencilmask
@get_c_fun gl glstencilop glStencilOp(fail::GLenum,zfail::GLenum,zpass::GLenum)::Void
export glstencilop
@get_c_fun gl glclearstencil glClearStencil(s::GLint)::Void
export glclearstencil
@get_c_fun gl gltexgend glTexGend(coord::GLenum,pname::GLenum,param::GLdouble)::Void
export gltexgend
@get_c_fun gl gltexgenf glTexGenf(coord::GLenum,pname::GLenum,param::GLfloat)::Void
export gltexgenf
@get_c_fun gl gltexgeni glTexGeni(coord::GLenum,pname::GLenum,param::GLint)::Void
export gltexgeni
@get_c_fun gl gltexgendv glTexGendv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export gltexgendv
@get_c_fun gl gltexgenfv glTexGenfv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export gltexgenfv
@get_c_fun gl gltexgeniv glTexGeniv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export gltexgeniv
@get_c_fun gl glgettexgendv glGetTexGendv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexgendv
@get_c_fun gl glgettexgenfv glGetTexGenfv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexgenfv
@get_c_fun gl glgettexgeniv glGetTexGeniv(coord::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexgeniv
@get_c_fun gl gltexenvf glTexEnvf(target::GLenum,pname::GLenum,param::GLfloat)::Void
export gltexenvf
@get_c_fun gl gltexenvi glTexEnvi(target::GLenum,pname::GLenum,param::GLint)::Void
export gltexenvi
@get_c_fun gl gltexenvfv glTexEnvfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export gltexenvfv
@get_c_fun gl gltexenviv glTexEnviv(target::GLenum,pname::GLenum,params::Ptr)::Void
export gltexenviv
@get_c_fun gl glgettexenvfv glGetTexEnvfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexenvfv
@get_c_fun gl glgettexenviv glGetTexEnviv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexenviv
@get_c_fun gl gltexparameterf glTexParameterf(target::GLenum,pname::GLenum,param::GLfloat)::Void
export gltexparameterf
@get_c_fun gl gltexparameteri glTexParameteri(target::GLenum,pname::GLenum,param::GLint)::Void
export gltexparameteri
@get_c_fun gl gltexparameterfv glTexParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export gltexparameterfv
@get_c_fun gl gltexparameteriv glTexParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export gltexparameteriv
@get_c_fun gl glgettexparameterfv glGetTexParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexparameterfv
@get_c_fun gl glgettexparameteriv glGetTexParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgettexparameteriv
@get_c_fun gl glgettexlevelparameterfv glGetTexLevelParameterfv(target::GLenum,level::GLint,pname::GLenum,params::Ptr)::Void
export glgettexlevelparameterfv
@get_c_fun gl glgettexlevelparameteriv glGetTexLevelParameteriv(target::GLenum,level::GLint,pname::GLenum,params::Ptr)::Void
export glgettexlevelparameteriv
@get_c_fun gl glteximage1d glTexImage1D(target::GLenum,level::GLint,internalformat::GLint,width::GLsizei,border::GLint,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export glteximage1d
@get_c_fun gl glteximage2d glTexImage2D(target::GLenum,level::GLint,internalformat::GLint,width::GLsizei,height::GLsizei,border::GLint,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export glteximage2d
@get_c_fun gl glgetteximage glGetTexImage(target::GLenum,level::GLint,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export glgetteximage
@get_c_fun gl glgentextures glGenTextures(n::GLsizei,textures::Ptr)::Void
export glgentextures
@get_c_fun gl gldeletetextures glDeleteTextures(n::GLsizei,textures::Ptr)::Void
export gldeletetextures
@get_c_fun gl glbindtexture glBindTexture(target::GLenum,texture::GLuint)::Void
export glbindtexture
@get_c_fun gl glprioritizetextures glPrioritizeTextures(n::GLsizei,textures::Ptr,priorities::Ptr)::Void
export glprioritizetextures
@get_c_fun gl glaretexturesresident glAreTexturesResident(n::GLsizei,textures::Ptr,residences::Ptr)::GLboolean
export glaretexturesresident
@get_c_fun gl glistexture glIsTexture(texture::GLuint)::GLboolean
export glistexture
@get_c_fun gl gltexsubimage1d glTexSubImage1D(target::GLenum,level::GLint,xoffset::GLint,width::GLsizei,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export gltexsubimage1d
@get_c_fun gl gltexsubimage2d glTexSubImage2D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,width::GLsizei,height::GLsizei,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export gltexsubimage2d
@get_c_fun gl glcopyteximage1d glCopyTexImage1D(target::GLenum,level::GLint,internalformat::GLenum,x::GLint,y::GLint,width::GLsizei,border::GLint)::Void
export glcopyteximage1d
@get_c_fun gl glcopyteximage2d glCopyTexImage2D(target::GLenum,level::GLint,internalformat::GLenum,x::GLint,y::GLint,width::GLsizei,height::GLsizei,border::GLint)::Void
export glcopyteximage2d
@get_c_fun gl glcopytexsubimage1d glCopyTexSubImage1D(target::GLenum,level::GLint,xoffset::GLint,x::GLint,y::GLint,width::GLsizei)::Void
export glcopytexsubimage1d
@get_c_fun gl glcopytexsubimage2d glCopyTexSubImage2D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,x::GLint,y::GLint,width::GLsizei,height::GLsizei)::Void
export glcopytexsubimage2d
@get_c_fun gl glmap1d glMap1d(target::GLenum,u1::GLdouble,u2::GLdouble,stride::GLint,order::GLint,points::Ptr)::Void
export glmap1d
@get_c_fun gl glmap1f glMap1f(target::GLenum,u1::GLfloat,u2::GLfloat,stride::GLint,order::GLint,points::Ptr)::Void
export glmap1f
@get_c_fun gl glmap2d glMap2d(target::GLenum,u1::GLdouble,u2::GLdouble,ustride::GLint,uorder::GLint,v1::GLdouble,v2::GLdouble,vstride::GLint,vorder::GLint,points::Ptr)::Void
export glmap2d
@get_c_fun gl glmap2f glMap2f(target::GLenum,u1::GLfloat,u2::GLfloat,ustride::GLint,uorder::GLint,v1::GLfloat,v2::GLfloat,vstride::GLint,vorder::GLint,points::Ptr)::Void
export glmap2f
@get_c_fun gl glgetmapdv glGetMapdv(target::GLenum,query::GLenum,v::Ptr)::Void
export glgetmapdv
@get_c_fun gl glgetmapfv glGetMapfv(target::GLenum,query::GLenum,v::Ptr)::Void
export glgetmapfv
@get_c_fun gl glgetmapiv glGetMapiv(target::GLenum,query::GLenum,v::Ptr)::Void
export glgetmapiv
@get_c_fun gl glevalcoord1d glEvalCoord1d(u::GLdouble)::Void
export glevalcoord1d
@get_c_fun gl glevalcoord1f glEvalCoord1f(u::GLfloat)::Void
export glevalcoord1f
@get_c_fun gl glevalcoord1dv glEvalCoord1dv(u::Ptr)::Void
export glevalcoord1dv
@get_c_fun gl glevalcoord1fv glEvalCoord1fv(u::Ptr)::Void
export glevalcoord1fv
@get_c_fun gl glevalcoord2d glEvalCoord2d(u::GLdouble,v::GLdouble)::Void
export glevalcoord2d
@get_c_fun gl glevalcoord2f glEvalCoord2f(u::GLfloat,v::GLfloat)::Void
export glevalcoord2f
@get_c_fun gl glevalcoord2dv glEvalCoord2dv(u::Ptr)::Void
export glevalcoord2dv
@get_c_fun gl glevalcoord2fv glEvalCoord2fv(u::Ptr)::Void
export glevalcoord2fv
@get_c_fun gl glmapgrid1d glMapGrid1d(un::GLint,u1::GLdouble,u2::GLdouble)::Void
export glmapgrid1d
@get_c_fun gl glmapgrid1f glMapGrid1f(un::GLint,u1::GLfloat,u2::GLfloat)::Void
export glmapgrid1f
@get_c_fun gl glmapgrid2d glMapGrid2d(un::GLint,u1::GLdouble,u2::GLdouble,vn::GLint,v1::GLdouble,v2::GLdouble)::Void
export glmapgrid2d
@get_c_fun gl glmapgrid2f glMapGrid2f(un::GLint,u1::GLfloat,u2::GLfloat,vn::GLint,v1::GLfloat,v2::GLfloat)::Void
export glmapgrid2f
@get_c_fun gl glevalpoint1 glEvalPoint1(i::GLint)::Void
export glevalpoint1
@get_c_fun gl glevalpoint2 glEvalPoint2(i::GLint,j::GLint)::Void
export glevalpoint2
@get_c_fun gl glevalmesh1 glEvalMesh1(mode::GLenum,i1::GLint,i2::GLint)::Void
export glevalmesh1
@get_c_fun gl glevalmesh2 glEvalMesh2(mode::GLenum,i1::GLint,i2::GLint,j1::GLint,j2::GLint)::Void
export glevalmesh2
@get_c_fun gl glfogf glFogf(pname::GLenum,param::GLfloat)::Void
export glfogf
@get_c_fun gl glfogi glFogi(pname::GLenum,param::GLint)::Void
export glfogi
@get_c_fun gl glfogfv glFogfv(pname::GLenum,params::Ptr)::Void
export glfogfv
@get_c_fun gl glfogiv glFogiv(pname::GLenum,params::Ptr)::Void
export glfogiv
@get_c_fun gl glfeedbackbuffer glFeedbackBuffer(size::GLsizei,_type::GLenum,buffer::Ptr)::Void
export glfeedbackbuffer
@get_c_fun gl glpassthrough glPassThrough(token::GLfloat)::Void
export glpassthrough
@get_c_fun gl glselectbuffer glSelectBuffer(size::GLsizei,buffer::Ptr)::Void
export glselectbuffer
@get_c_fun gl glinitnames glInitNames()::Void
export glinitnames
@get_c_fun gl glloadname glLoadName(name::GLuint)::Void
export glloadname
@get_c_fun gl glpushname glPushName(name::GLuint)::Void
export glpushname
@get_c_fun gl glpopname glPopName()::Void
export glpopname
@get_c_fun gl gldrawrangeelements glDrawRangeElements(mode::GLenum,start::GLuint,_end::GLuint,count::GLsizei,_type::GLenum,indices::Ptr)::Void
export gldrawrangeelements
@get_c_fun gl glteximage3d glTexImage3D(target::GLenum,level::GLint,internalformat::GLint,width::GLsizei,height::GLsizei,depth::GLsizei,border::GLint,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export glteximage3d
@get_c_fun gl gltexsubimage3d glTexSubImage3D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,zoffset::GLint,width::GLsizei,height::GLsizei,depth::GLsizei,format::GLenum,_type::GLenum,pixels::Ptr)::Void
export gltexsubimage3d
@get_c_fun gl glcopytexsubimage3d glCopyTexSubImage3D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,zoffset::GLint,x::GLint,y::GLint,width::GLsizei,height::GLsizei)::Void
export glcopytexsubimage3d
@get_c_fun gl glcolortable glColorTable(target::GLenum,internalformat::GLenum,width::GLsizei,format::GLenum,_type::GLenum,table::Ptr)::Void
export glcolortable
@get_c_fun gl glcolorsubtable glColorSubTable(target::GLenum,start::GLsizei,count::GLsizei,format::GLenum,_type::GLenum,data::Ptr)::Void
export glcolorsubtable
@get_c_fun gl glcolortableparameteriv glColorTableParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glcolortableparameteriv
@get_c_fun gl glcolortableparameterfv glColorTableParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glcolortableparameterfv
@get_c_fun gl glcopycolorsubtable glCopyColorSubTable(target::GLenum,start::GLsizei,x::GLint,y::GLint,width::GLsizei)::Void
export glcopycolorsubtable
@get_c_fun gl glcopycolortable glCopyColorTable(target::GLenum,internalformat::GLenum,x::GLint,y::GLint,width::GLsizei)::Void
export glcopycolortable
@get_c_fun gl glgetcolortable glGetColorTable(target::GLenum,format::GLenum,_type::GLenum,table::Ptr)::Void
export glgetcolortable
@get_c_fun gl glgetcolortableparameterfv glGetColorTableParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetcolortableparameterfv
@get_c_fun gl glgetcolortableparameteriv glGetColorTableParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetcolortableparameteriv
@get_c_fun gl glblendequation glBlendEquation(mode::GLenum)::Void
export glblendequation
@get_c_fun gl glblendcolor glBlendColor(red::GLclampf,green::GLclampf,blue::GLclampf,alpha::GLclampf)::Void
export glblendcolor
@get_c_fun gl glhistogram glHistogram(target::GLenum,width::GLsizei,internalformat::GLenum,sink::GLboolean)::Void
export glhistogram
@get_c_fun gl glresethistogram glResetHistogram(target::GLenum)::Void
export glresethistogram
@get_c_fun gl glgethistogram glGetHistogram(target::GLenum,reset::GLboolean,format::GLenum,_type::GLenum,values::Ptr)::Void
export glgethistogram
@get_c_fun gl glgethistogramparameterfv glGetHistogramParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgethistogramparameterfv
@get_c_fun gl glgethistogramparameteriv glGetHistogramParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgethistogramparameteriv
@get_c_fun gl glminmax glMinmax(target::GLenum,internalformat::GLenum,sink::GLboolean)::Void
export glminmax
@get_c_fun gl glresetminmax glResetMinmax(target::GLenum)::Void
export glresetminmax
@get_c_fun gl glgetminmax glGetMinmax(target::GLenum,reset::GLboolean,format::GLenum,types::GLenum,values::Ptr)::Void
export glgetminmax
@get_c_fun gl glgetminmaxparameterfv glGetMinmaxParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetminmaxparameterfv
@get_c_fun gl glgetminmaxparameteriv glGetMinmaxParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetminmaxparameteriv
@get_c_fun gl glconvolutionfilter1d glConvolutionFilter1D(target::GLenum,internalformat::GLenum,width::GLsizei,format::GLenum,_type::GLenum,image::Ptr)::Void
export glconvolutionfilter1d
@get_c_fun gl glconvolutionfilter2d glConvolutionFilter2D(target::GLenum,internalformat::GLenum,width::GLsizei,height::GLsizei,format::GLenum,_type::GLenum,image::Ptr)::Void
export glconvolutionfilter2d
@get_c_fun gl glconvolutionparameterf glConvolutionParameterf(target::GLenum,pname::GLenum,params::GLfloat)::Void
export glconvolutionparameterf
@get_c_fun gl glconvolutionparameterfv glConvolutionParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glconvolutionparameterfv
@get_c_fun gl glconvolutionparameteri glConvolutionParameteri(target::GLenum,pname::GLenum,params::GLint)::Void
export glconvolutionparameteri
@get_c_fun gl glconvolutionparameteriv glConvolutionParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glconvolutionparameteriv
@get_c_fun gl glcopyconvolutionfilter1d glCopyConvolutionFilter1D(target::GLenum,internalformat::GLenum,x::GLint,y::GLint,width::GLsizei)::Void
export glcopyconvolutionfilter1d
@get_c_fun gl glcopyconvolutionfilter2d glCopyConvolutionFilter2D(target::GLenum,internalformat::GLenum,x::GLint,y::GLint,width::GLsizei,height::GLsizei)::Void
export glcopyconvolutionfilter2d
@get_c_fun gl glgetconvolutionfilter glGetConvolutionFilter(target::GLenum,format::GLenum,_type::GLenum,image::Ptr)::Void
export glgetconvolutionfilter
@get_c_fun gl glgetconvolutionparameterfv glGetConvolutionParameterfv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetconvolutionparameterfv
@get_c_fun gl glgetconvolutionparameteriv glGetConvolutionParameteriv(target::GLenum,pname::GLenum,params::Ptr)::Void
export glgetconvolutionparameteriv
@get_c_fun gl glseparablefilter2d glSeparableFilter2D(target::GLenum,internalformat::GLenum,width::GLsizei,height::GLsizei,format::GLenum,_type::GLenum,row::Ptr,column::Ptr)::Void
export glseparablefilter2d
@get_c_fun gl glgetseparablefilter glGetSeparableFilter(target::GLenum,format::GLenum,_type::GLenum,row::Ptr,column::Ptr,span::Ptr)::Void
export glgetseparablefilter
@get_c_fun gl glactivetexture glActiveTexture(texture::GLenum)::Void
export glactivetexture
@get_c_fun gl glclientactivetexture glClientActiveTexture(texture::GLenum)::Void
export glclientactivetexture
@get_c_fun gl glcompressedteximage1d glCompressedTexImage1D(target::GLenum,level::GLint,internalformat::GLenum,width::GLsizei,border::GLint,imagesize::GLsizei,data::Ptr)::Void
export glcompressedteximage1d
@get_c_fun gl glcompressedteximage2d glCompressedTexImage2D(target::GLenum,level::GLint,internalformat::GLenum,width::GLsizei,height::GLsizei,border::GLint,imagesize::GLsizei,data::Ptr)::Void
export glcompressedteximage2d
@get_c_fun gl glcompressedteximage3d glCompressedTexImage3D(target::GLenum,level::GLint,internalformat::GLenum,width::GLsizei,height::GLsizei,depth::GLsizei,border::GLint,imagesize::GLsizei,data::Ptr)::Void
export glcompressedteximage3d
@get_c_fun gl glcompressedtexsubimage1d glCompressedTexSubImage1D(target::GLenum,level::GLint,xoffset::GLint,width::GLsizei,format::GLenum,imagesize::GLsizei,data::Ptr)::Void
export glcompressedtexsubimage1d
@get_c_fun gl glcompressedtexsubimage2d glCompressedTexSubImage2D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,width::GLsizei,height::GLsizei,format::GLenum,imagesize::GLsizei,data::Ptr)::Void
export glcompressedtexsubimage2d
@get_c_fun gl glcompressedtexsubimage3d glCompressedTexSubImage3D(target::GLenum,level::GLint,xoffset::GLint,yoffset::GLint,zoffset::GLint,width::GLsizei,height::GLsizei,depth::GLsizei,format::GLenum,imagesize::GLsizei,data::Ptr)::Void
export glcompressedtexsubimage3d
@get_c_fun gl glgetcompressedteximage glGetCompressedTexImage(target::GLenum,lod::GLint,img::Ptr)::Void
export glgetcompressedteximage
@get_c_fun gl glmultitexcoord1d glMultiTexCoord1d(target::GLenum,s::GLdouble)::Void
export glmultitexcoord1d
@get_c_fun gl glmultitexcoord1dv glMultiTexCoord1dv(target::GLenum,v::Ptr)::Void
export glmultitexcoord1dv
@get_c_fun gl glmultitexcoord1f glMultiTexCoord1f(target::GLenum,s::GLfloat)::Void
export glmultitexcoord1f
@get_c_fun gl glmultitexcoord1fv glMultiTexCoord1fv(target::GLenum,v::Ptr)::Void
export glmultitexcoord1fv
@get_c_fun gl glmultitexcoord1i glMultiTexCoord1i(target::GLenum,s::GLint)::Void
export glmultitexcoord1i
@get_c_fun gl glmultitexcoord1iv glMultiTexCoord1iv(target::GLenum,v::Ptr)::Void
export glmultitexcoord1iv
@get_c_fun gl glmultitexcoord1s glMultiTexCoord1s(target::GLenum,s::GLshort)::Void
export glmultitexcoord1s
@get_c_fun gl glmultitexcoord1sv glMultiTexCoord1sv(target::GLenum,v::Ptr)::Void
export glmultitexcoord1sv
@get_c_fun gl glmultitexcoord2d glMultiTexCoord2d(target::GLenum,s::GLdouble,t::GLdouble)::Void
export glmultitexcoord2d
@get_c_fun gl glmultitexcoord2dv glMultiTexCoord2dv(target::GLenum,v::Ptr)::Void
export glmultitexcoord2dv
@get_c_fun gl glmultitexcoord2f glMultiTexCoord2f(target::GLenum,s::GLfloat,t::GLfloat)::Void
export glmultitexcoord2f
@get_c_fun gl glmultitexcoord2fv glMultiTexCoord2fv(target::GLenum,v::Ptr)::Void
export glmultitexcoord2fv
@get_c_fun gl glmultitexcoord2i glMultiTexCoord2i(target::GLenum,s::GLint,t::GLint)::Void
export glmultitexcoord2i
@get_c_fun gl glmultitexcoord2iv glMultiTexCoord2iv(target::GLenum,v::Ptr)::Void
export glmultitexcoord2iv
@get_c_fun gl glmultitexcoord2s glMultiTexCoord2s(target::GLenum,s::GLshort,t::GLshort)::Void
export glmultitexcoord2s
@get_c_fun gl glmultitexcoord2sv glMultiTexCoord2sv(target::GLenum,v::Ptr)::Void
export glmultitexcoord2sv
@get_c_fun gl glmultitexcoord3d glMultiTexCoord3d(target::GLenum,s::GLdouble,t::GLdouble,r::GLdouble)::Void
export glmultitexcoord3d
@get_c_fun gl glmultitexcoord3dv glMultiTexCoord3dv(target::GLenum,v::Ptr)::Void
export glmultitexcoord3dv
@get_c_fun gl glmultitexcoord3f glMultiTexCoord3f(target::GLenum,s::GLfloat,t::GLfloat,r::GLfloat)::Void
export glmultitexcoord3f
@get_c_fun gl glmultitexcoord3fv glMultiTexCoord3fv(target::GLenum,v::Ptr)::Void
export glmultitexcoord3fv
@get_c_fun gl glmultitexcoord3i glMultiTexCoord3i(target::GLenum,s::GLint,t::GLint,r::GLint)::Void
export glmultitexcoord3i
@get_c_fun gl glmultitexcoord3iv glMultiTexCoord3iv(target::GLenum,v::Ptr)::Void
export glmultitexcoord3iv
@get_c_fun gl glmultitexcoord3s glMultiTexCoord3s(target::GLenum,s::GLshort,t::GLshort,r::GLshort)::Void
export glmultitexcoord3s
@get_c_fun gl glmultitexcoord3sv glMultiTexCoord3sv(target::GLenum,v::Ptr)::Void
export glmultitexcoord3sv
@get_c_fun gl glmultitexcoord4d glMultiTexCoord4d(target::GLenum,s::GLdouble,t::GLdouble,r::GLdouble,q::GLdouble)::Void
export glmultitexcoord4d
@get_c_fun gl glmultitexcoord4dv glMultiTexCoord4dv(target::GLenum,v::Ptr)::Void
export glmultitexcoord4dv
@get_c_fun gl glmultitexcoord4f glMultiTexCoord4f(target::GLenum,s::GLfloat,t::GLfloat,r::GLfloat,q::GLfloat)::Void
export glmultitexcoord4f
@get_c_fun gl glmultitexcoord4fv glMultiTexCoord4fv(target::GLenum,v::Ptr)::Void
export glmultitexcoord4fv
@get_c_fun gl glmultitexcoord4i glMultiTexCoord4i(target::GLenum,s::GLint,t::GLint,r::GLint,q::GLint)::Void
export glmultitexcoord4i
@get_c_fun gl glmultitexcoord4iv glMultiTexCoord4iv(target::GLenum,v::Ptr)::Void
export glmultitexcoord4iv
@get_c_fun gl glmultitexcoord4s glMultiTexCoord4s(target::GLenum,s::GLshort,t::GLshort,r::GLshort,q::GLshort)::Void
export glmultitexcoord4s
@get_c_fun gl glmultitexcoord4sv glMultiTexCoord4sv(target::GLenum,v::Ptr)::Void
export glmultitexcoord4sv
@get_c_fun gl glloadtransposematrixd glLoadTransposeMatrixd(m::GLdouble)::Void
export glloadtransposematrixd
@get_c_fun gl glloadtransposematrixf glLoadTransposeMatrixf(m::GLfloat)::Void
export glloadtransposematrixf
@get_c_fun gl glmulttransposematrixd glMultTransposeMatrixd(m::GLdouble)::Void
export glmulttransposematrixd
@get_c_fun gl glmulttransposematrixf glMultTransposeMatrixf(m::GLfloat)::Void
export glmulttransposematrixf
@get_c_fun gl glsamplecoverage glSampleCoverage(value::GLclampf,invert::GLboolean)::Void
export glsamplecoverage
@get_c_fun gl glactivetexturearb glActiveTextureARB(texture::GLenum)::Void
export glactivetexturearb
@get_c_fun gl glclientactivetexturearb glClientActiveTextureARB(texture::GLenum)::Void
export glclientactivetexturearb
@get_c_fun gl glmultitexcoord1darb glMultiTexCoord1dARB(target::GLenum,s::GLdouble)::Void
export glmultitexcoord1darb
@get_c_fun gl glmultitexcoord1dvarb glMultiTexCoord1dvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord1dvarb
@get_c_fun gl glmultitexcoord1farb glMultiTexCoord1fARB(target::GLenum,s::GLfloat)::Void
export glmultitexcoord1farb
@get_c_fun gl glmultitexcoord1fvarb glMultiTexCoord1fvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord1fvarb
@get_c_fun gl glmultitexcoord1iarb glMultiTexCoord1iARB(target::GLenum,s::GLint)::Void
export glmultitexcoord1iarb
@get_c_fun gl glmultitexcoord1ivarb glMultiTexCoord1ivARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord1ivarb
@get_c_fun gl glmultitexcoord1sarb glMultiTexCoord1sARB(target::GLenum,s::GLshort)::Void
export glmultitexcoord1sarb
@get_c_fun gl glmultitexcoord1svarb glMultiTexCoord1svARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord1svarb
@get_c_fun gl glmultitexcoord2darb glMultiTexCoord2dARB(target::GLenum,s::GLdouble,t::GLdouble)::Void
export glmultitexcoord2darb
@get_c_fun gl glmultitexcoord2dvarb glMultiTexCoord2dvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord2dvarb
@get_c_fun gl glmultitexcoord2farb glMultiTexCoord2fARB(target::GLenum,s::GLfloat,t::GLfloat)::Void
export glmultitexcoord2farb
@get_c_fun gl glmultitexcoord2fvarb glMultiTexCoord2fvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord2fvarb
@get_c_fun gl glmultitexcoord2iarb glMultiTexCoord2iARB(target::GLenum,s::GLint,t::GLint)::Void
export glmultitexcoord2iarb
@get_c_fun gl glmultitexcoord2ivarb glMultiTexCoord2ivARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord2ivarb
@get_c_fun gl glmultitexcoord2sarb glMultiTexCoord2sARB(target::GLenum,s::GLshort,t::GLshort)::Void
export glmultitexcoord2sarb
@get_c_fun gl glmultitexcoord2svarb glMultiTexCoord2svARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord2svarb
@get_c_fun gl glmultitexcoord3darb glMultiTexCoord3dARB(target::GLenum,s::GLdouble,t::GLdouble,r::GLdouble)::Void
export glmultitexcoord3darb
@get_c_fun gl glmultitexcoord3dvarb glMultiTexCoord3dvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord3dvarb
@get_c_fun gl glmultitexcoord3farb glMultiTexCoord3fARB(target::GLenum,s::GLfloat,t::GLfloat,r::GLfloat)::Void
export glmultitexcoord3farb
@get_c_fun gl glmultitexcoord3fvarb glMultiTexCoord3fvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord3fvarb
@get_c_fun gl glmultitexcoord3iarb glMultiTexCoord3iARB(target::GLenum,s::GLint,t::GLint,r::GLint)::Void
export glmultitexcoord3iarb
@get_c_fun gl glmultitexcoord3ivarb glMultiTexCoord3ivARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord3ivarb
@get_c_fun gl glmultitexcoord3sarb glMultiTexCoord3sARB(target::GLenum,s::GLshort,t::GLshort,r::GLshort)::Void
export glmultitexcoord3sarb
@get_c_fun gl glmultitexcoord3svarb glMultiTexCoord3svARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord3svarb
@get_c_fun gl glmultitexcoord4darb glMultiTexCoord4dARB(target::GLenum,s::GLdouble,t::GLdouble,r::GLdouble,q::GLdouble)::Void
export glmultitexcoord4darb
@get_c_fun gl glmultitexcoord4dvarb glMultiTexCoord4dvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord4dvarb
@get_c_fun gl glmultitexcoord4farb glMultiTexCoord4fARB(target::GLenum,s::GLfloat,t::GLfloat,r::GLfloat,q::GLfloat)::Void
export glmultitexcoord4farb
@get_c_fun gl glmultitexcoord4fvarb glMultiTexCoord4fvARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord4fvarb
@get_c_fun gl glmultitexcoord4iarb glMultiTexCoord4iARB(target::GLenum,s::GLint,t::GLint,r::GLint,q::GLint)::Void
export glmultitexcoord4iarb
@get_c_fun gl glmultitexcoord4ivarb glMultiTexCoord4ivARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord4ivarb
@get_c_fun gl glmultitexcoord4sarb glMultiTexCoord4sARB(target::GLenum,s::GLshort,t::GLshort,r::GLshort,q::GLshort)::Void
export glmultitexcoord4sarb
@get_c_fun gl glmultitexcoord4svarb glMultiTexCoord4svARB(target::GLenum,v::Ptr)::Void
export glmultitexcoord4svarb
typealias ptrdiff_t Int64
export ptrdiff_t
typealias size_t Int64
export size_t
typealias wchar_t Int32
export wchar_t
typealias GLchar Uint8
export GLchar
typealias GLintptr ptrdiff_t
export GLintptr
typealias GLsizeiptr ptrdiff_t
export GLsizeiptr
typealias GLintptrARB ptrdiff_t
export GLintptrARB
typealias GLsizeiptrARB ptrdiff_t
export GLsizeiptrARB
typealias GLcharARB Uint8
export GLcharARB
typealias GLhandleARB Uint32
export GLhandleARB
typealias GLhalfARB Uint16
export GLhalfARB
typealias GLhalfNV Uint16
export GLhalfNV
typealias int8_t Uint8
export int8_t
typealias int16_t Int16
export int16_t
typealias int32_t Int32
export int32_t
typealias int64_t Int64
export int64_t
typealias uint8_t Uint8
export uint8_t
typealias uint16_t Uint16
export uint16_t
typealias uint32_t Uint32
export uint32_t
typealias uint64_t Uint64
export uint64_t
typealias int_least8_t Uint8
export int_least8_t
typealias int_least16_t Int16
export int_least16_t
typealias int_least32_t Int32
export int_least32_t
typealias int_least64_t Int64
export int_least64_t
typealias uint_least8_t Uint8
export uint_least8_t
typealias uint_least16_t Uint16
export uint_least16_t
typealias uint_least32_t Uint32
export uint_least32_t
typealias uint_least64_t Uint64
export uint_least64_t
typealias int_fast8_t Uint8
export int_fast8_t
typealias int_fast16_t Int64
export int_fast16_t
typealias int_fast32_t Int64
export int_fast32_t
typealias int_fast64_t Int64
export int_fast64_t
typealias uint_fast8_t Uint8
export uint_fast8_t
typealias uint_fast16_t Uint64
export uint_fast16_t
typealias uint_fast32_t Uint64
export uint_fast32_t
typealias uint_fast64_t Uint64
export uint_fast64_t
typealias intptr_t Int64
export intptr_t
typealias uintptr_t Uint64
export uintptr_t
typealias intmax_t Int64
export intmax_t
typealias uintmax_t Uint64
export uintmax_t
typealias __gwchar_t Int32
export __gwchar_t
@get_c_fun gl imaxabs imaxabs(__n::intmax_t)::intmax_t
export imaxabs
@get_c_fun gl imaxdiv imaxdiv(__numer::intmax_t,__denom::intmax_t)::imaxdiv_t
export imaxdiv
@get_c_fun gl strtoimax strtoimax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::intmax_t
export strtoimax
@get_c_fun gl strtoumax strtoumax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::uintmax_t
export strtoumax
@get_c_fun gl wcstoimax wcstoimax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::intmax_t
export wcstoimax
@get_c_fun gl wcstoumax wcstoumax(__nptr::Ptr,__endptr::Ptr,__base::Int32)::uintmax_t
export wcstoumax
typealias GLint64EXT int64_t
export GLint64EXT
typealias GLuint64EXT uint64_t
export GLuint64EXT
typealias GLint64 int64_t
export GLint64
typealias GLuint64 uint64_t
export GLuint64
typealias GLvdpauSurfaceNV GLintptr
export GLvdpauSurfaceNV
@get_c_fun gl glcreatedebugobjectmesa glCreateDebugObjectMESA()::GLhandleARB
export glcreatedebugobjectmesa
@get_c_fun gl glcleardebuglogmesa glClearDebugLogMESA(obj::GLhandleARB,logtype::GLenum,shadertype::GLenum)::Void
export glcleardebuglogmesa
@get_c_fun gl glgetdebuglogmesa glGetDebugLogMESA(obj::GLhandleARB,logtype::GLenum,shadertype::GLenum,maxlength::GLsizei,length::Ptr,debuglog::Ptr)::Void
export glgetdebuglogmesa
@get_c_fun gl glgetdebugloglengthmesa glGetDebugLogLengthMESA(obj::GLhandleARB,logtype::GLenum,shadertype::GLenum)::GLsizei
export glgetdebugloglengthmesa
@get_c_fun gl glprogramcallbackmesa glProgramCallbackMESA(target::GLenum,callback::GLprogramcallbackMESA,data::Ptr)::Void
export glprogramcallbackmesa
@get_c_fun gl glgetprogramregisterfvmesa glGetProgramRegisterfvMESA(target::GLenum,len::GLsizei,name::Ptr,v::Ptr)::Void
export glgetprogramregisterfvmesa
@get_c_fun gl glblendequationseparateati glBlendEquationSeparateATI(modergb::GLenum,modea::GLenum)::Void
export glblendequationseparateati
typealias GLeglImageOES Ptr
export GLeglImageOES
const GL_VERSION_1_1 = 1
export GL_VERSION_1_1
const GL_VERSION_1_2 = 1
export GL_VERSION_1_2
const GL_VERSION_1_3 = 1
export GL_VERSION_1_3
const GL_ARB_imaging = 1
export GL_ARB_imaging
const GL_FALSE = 0x0
export GL_FALSE
const GL_TRUE = 0x1
export GL_TRUE
const GL_BYTE = 0x1400
export GL_BYTE
const GL_UNSIGNED_BYTE = 0x1401
export GL_UNSIGNED_BYTE
const GL_SHORT = 0x1402
export GL_SHORT
const GL_UNSIGNED_SHORT = 0x1403
export GL_UNSIGNED_SHORT
const GL_INT = 0x1404
export GL_INT
const GL_UNSIGNED_INT = 0x1405
export GL_UNSIGNED_INT
const GL_FLOAT = 0x1406
export GL_FLOAT
const GL_2_BYTES = 0x1407
export GL_2_BYTES
const GL_3_BYTES = 0x1408
export GL_3_BYTES
const GL_4_BYTES = 0x1409
export GL_4_BYTES
const GL_DOUBLE = 0x140A
export GL_DOUBLE
const GL_POINTS = 0x0000
export GL_POINTS
const GL_LINES = 0x0001
export GL_LINES
const GL_LINE_LOOP = 0x0002
export GL_LINE_LOOP
const GL_LINE_STRIP = 0x0003
export GL_LINE_STRIP
const GL_TRIANGLES = 0x0004
export GL_TRIANGLES
const GL_TRIANGLE_STRIP = 0x0005
export GL_TRIANGLE_STRIP
const GL_TRIANGLE_FAN = 0x0006
export GL_TRIANGLE_FAN
const GL_QUADS = 0x0007
export GL_QUADS
const GL_QUAD_STRIP = 0x0008
export GL_QUAD_STRIP
const GL_POLYGON = 0x0009
export GL_POLYGON
const GL_VERTEX_ARRAY = 0x8074
export GL_VERTEX_ARRAY
const GL_NORMAL_ARRAY = 0x8075
export GL_NORMAL_ARRAY
const GL_COLOR_ARRAY = 0x8076
export GL_COLOR_ARRAY
const GL_INDEX_ARRAY = 0x8077
export GL_INDEX_ARRAY
const GL_TEXTURE_COORD_ARRAY = 0x8078
export GL_TEXTURE_COORD_ARRAY
const GL_EDGE_FLAG_ARRAY = 0x8079
export GL_EDGE_FLAG_ARRAY
const GL_VERTEX_ARRAY_SIZE = 0x807A
export GL_VERTEX_ARRAY_SIZE
const GL_VERTEX_ARRAY_TYPE = 0x807B
export GL_VERTEX_ARRAY_TYPE
const GL_VERTEX_ARRAY_STRIDE = 0x807C
export GL_VERTEX_ARRAY_STRIDE
const GL_NORMAL_ARRAY_TYPE = 0x807E
export GL_NORMAL_ARRAY_TYPE
const GL_NORMAL_ARRAY_STRIDE = 0x807F
export GL_NORMAL_ARRAY_STRIDE
const GL_COLOR_ARRAY_SIZE = 0x8081
export GL_COLOR_ARRAY_SIZE
const GL_COLOR_ARRAY_TYPE = 0x8082
export GL_COLOR_ARRAY_TYPE
const GL_COLOR_ARRAY_STRIDE = 0x8083
export GL_COLOR_ARRAY_STRIDE
const GL_INDEX_ARRAY_TYPE = 0x8085
export GL_INDEX_ARRAY_TYPE
const GL_INDEX_ARRAY_STRIDE = 0x8086
export GL_INDEX_ARRAY_STRIDE
const GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088
export GL_TEXTURE_COORD_ARRAY_SIZE
const GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089
export GL_TEXTURE_COORD_ARRAY_TYPE
const GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A
export GL_TEXTURE_COORD_ARRAY_STRIDE
const GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C
export GL_EDGE_FLAG_ARRAY_STRIDE
const GL_VERTEX_ARRAY_POINTER = 0x808E
export GL_VERTEX_ARRAY_POINTER
const GL_NORMAL_ARRAY_POINTER = 0x808F
export GL_NORMAL_ARRAY_POINTER
const GL_COLOR_ARRAY_POINTER = 0x8090
export GL_COLOR_ARRAY_POINTER
const GL_INDEX_ARRAY_POINTER = 0x8091
export GL_INDEX_ARRAY_POINTER
const GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092
export GL_TEXTURE_COORD_ARRAY_POINTER
const GL_EDGE_FLAG_ARRAY_POINTER = 0x8093
export GL_EDGE_FLAG_ARRAY_POINTER
const GL_V2F = 0x2A20
export GL_V2F
const GL_V3F = 0x2A21
export GL_V3F
const GL_C4UB_V2F = 0x2A22
export GL_C4UB_V2F
const GL_C4UB_V3F = 0x2A23
export GL_C4UB_V3F
const GL_C3F_V3F = 0x2A24
export GL_C3F_V3F
const GL_N3F_V3F = 0x2A25
export GL_N3F_V3F
const GL_C4F_N3F_V3F = 0x2A26
export GL_C4F_N3F_V3F
const GL_T2F_V3F = 0x2A27
export GL_T2F_V3F
const GL_T4F_V4F = 0x2A28
export GL_T4F_V4F
const GL_T2F_C4UB_V3F = 0x2A29
export GL_T2F_C4UB_V3F
const GL_T2F_C3F_V3F = 0x2A2A
export GL_T2F_C3F_V3F
const GL_T2F_N3F_V3F = 0x2A2B
export GL_T2F_N3F_V3F
const GL_T2F_C4F_N3F_V3F = 0x2A2C
export GL_T2F_C4F_N3F_V3F
const GL_T4F_C4F_N3F_V4F = 0x2A2D
export GL_T4F_C4F_N3F_V4F
const GL_MATRIX_MODE = 0x0BA0
export GL_MATRIX_MODE
const GL_MODELVIEW = 0x1700
export GL_MODELVIEW
const GL_PROJECTION = 0x1701
export GL_PROJECTION
const GL_TEXTURE = 0x1702
export GL_TEXTURE
const GL_POINT_SMOOTH = 0x0B10
export GL_POINT_SMOOTH
const GL_POINT_SIZE = 0x0B11
export GL_POINT_SIZE
const GL_POINT_SIZE_GRANULARITY = 0x0B13
export GL_POINT_SIZE_GRANULARITY
const GL_POINT_SIZE_RANGE = 0x0B12
export GL_POINT_SIZE_RANGE
const GL_LINE_SMOOTH = 0x0B20
export GL_LINE_SMOOTH
const GL_LINE_STIPPLE = 0x0B24
export GL_LINE_STIPPLE
const GL_LINE_STIPPLE_PATTERN = 0x0B25
export GL_LINE_STIPPLE_PATTERN
const GL_LINE_STIPPLE_REPEAT = 0x0B26
export GL_LINE_STIPPLE_REPEAT
const GL_LINE_WIDTH = 0x0B21
export GL_LINE_WIDTH
const GL_LINE_WIDTH_GRANULARITY = 0x0B23
export GL_LINE_WIDTH_GRANULARITY
const GL_LINE_WIDTH_RANGE = 0x0B22
export GL_LINE_WIDTH_RANGE
const GL_POINT = 0x1B00
export GL_POINT
const GL_LINE = 0x1B01
export GL_LINE
const GL_FILL = 0x1B02
export GL_FILL
const GL_CW = 0x0900
export GL_CW
const GL_CCW = 0x0901
export GL_CCW
const GL_FRONT = 0x0404
export GL_FRONT
const GL_BACK = 0x0405
export GL_BACK
const GL_POLYGON_MODE = 0x0B40
export GL_POLYGON_MODE
const GL_POLYGON_SMOOTH = 0x0B41
export GL_POLYGON_SMOOTH
const GL_POLYGON_STIPPLE = 0x0B42
export GL_POLYGON_STIPPLE
const GL_EDGE_FLAG = 0x0B43
export GL_EDGE_FLAG
const GL_CULL_FACE = 0x0B44
export GL_CULL_FACE
const GL_CULL_FACE_MODE = 0x0B45
export GL_CULL_FACE_MODE
const GL_FRONT_FACE = 0x0B46
export GL_FRONT_FACE
const GL_POLYGON_OFFSET_FACTOR = 0x8038
export GL_POLYGON_OFFSET_FACTOR
const GL_POLYGON_OFFSET_UNITS = 0x2A00
export GL_POLYGON_OFFSET_UNITS
const GL_POLYGON_OFFSET_POINT = 0x2A01
export GL_POLYGON_OFFSET_POINT
const GL_POLYGON_OFFSET_LINE = 0x2A02
export GL_POLYGON_OFFSET_LINE
const GL_POLYGON_OFFSET_FILL = 0x8037
export GL_POLYGON_OFFSET_FILL
const GL_COMPILE = 0x1300
export GL_COMPILE
const GL_COMPILE_AND_EXECUTE = 0x1301
export GL_COMPILE_AND_EXECUTE
const GL_LIST_BASE = 0x0B32
export GL_LIST_BASE
const GL_LIST_INDEX = 0x0B33
export GL_LIST_INDEX
const GL_LIST_MODE = 0x0B30
export GL_LIST_MODE
const GL_NEVER = 0x0200
export GL_NEVER
const GL_LESS = 0x0201
export GL_LESS
const GL_EQUAL = 0x0202
export GL_EQUAL
const GL_LEQUAL = 0x0203
export GL_LEQUAL
const GL_GREATER = 0x0204
export GL_GREATER
const GL_NOTEQUAL = 0x0205
export GL_NOTEQUAL
const GL_GEQUAL = 0x0206
export GL_GEQUAL
const GL_ALWAYS = 0x0207
export GL_ALWAYS
const GL_DEPTH_TEST = 0x0B71
export GL_DEPTH_TEST
const GL_DEPTH_BITS = 0x0D56
export GL_DEPTH_BITS
const GL_DEPTH_CLEAR_VALUE = 0x0B73
export GL_DEPTH_CLEAR_VALUE
const GL_DEPTH_FUNC = 0x0B74
export GL_DEPTH_FUNC
const GL_DEPTH_RANGE = 0x0B70
export GL_DEPTH_RANGE
const GL_DEPTH_WRITEMASK = 0x0B72
export GL_DEPTH_WRITEMASK
const GL_DEPTH_COMPONENT = 0x1902
export GL_DEPTH_COMPONENT
const GL_LIGHTING = 0x0B50
export GL_LIGHTING
const GL_LIGHT0 = 0x4000
export GL_LIGHT0
const GL_LIGHT1 = 0x4001
export GL_LIGHT1
const GL_LIGHT2 = 0x4002
export GL_LIGHT2
const GL_LIGHT3 = 0x4003
export GL_LIGHT3
const GL_LIGHT4 = 0x4004
export GL_LIGHT4
const GL_LIGHT5 = 0x4005
export GL_LIGHT5
const GL_LIGHT6 = 0x4006
export GL_LIGHT6
const GL_LIGHT7 = 0x4007
export GL_LIGHT7
const GL_SPOT_EXPONENT = 0x1205
export GL_SPOT_EXPONENT
const GL_SPOT_CUTOFF = 0x1206
export GL_SPOT_CUTOFF
const GL_CONSTANT_ATTENUATION = 0x1207
export GL_CONSTANT_ATTENUATION
const GL_LINEAR_ATTENUATION = 0x1208
export GL_LINEAR_ATTENUATION
const GL_QUADRATIC_ATTENUATION = 0x1209
export GL_QUADRATIC_ATTENUATION
const GL_AMBIENT = 0x1200
export GL_AMBIENT
const GL_DIFFUSE = 0x1201
export GL_DIFFUSE
const GL_SPECULAR = 0x1202
export GL_SPECULAR
const GL_SHININESS = 0x1601
export GL_SHININESS
const GL_EMISSION = 0x1600
export GL_EMISSION
const GL_POSITION = 0x1203
export GL_POSITION
const GL_SPOT_DIRECTION = 0x1204
export GL_SPOT_DIRECTION
const GL_AMBIENT_AND_DIFFUSE = 0x1602
export GL_AMBIENT_AND_DIFFUSE
const GL_COLOR_INDEXES = 0x1603
export GL_COLOR_INDEXES
const GL_LIGHT_MODEL_TWO_SIDE = 0x0B52
export GL_LIGHT_MODEL_TWO_SIDE
const GL_LIGHT_MODEL_LOCAL_VIEWER = 0x0B51
export GL_LIGHT_MODEL_LOCAL_VIEWER
const GL_LIGHT_MODEL_AMBIENT = 0x0B53
export GL_LIGHT_MODEL_AMBIENT
const GL_FRONT_AND_BACK = 0x0408
export GL_FRONT_AND_BACK
const GL_SHADE_MODEL = 0x0B54
export GL_SHADE_MODEL
const GL_FLAT = 0x1D00
export GL_FLAT
const GL_SMOOTH = 0x1D01
export GL_SMOOTH
const GL_COLOR_MATERIAL = 0x0B57
export GL_COLOR_MATERIAL
const GL_COLOR_MATERIAL_FACE = 0x0B55
export GL_COLOR_MATERIAL_FACE
const GL_COLOR_MATERIAL_PARAMETER = 0x0B56
export GL_COLOR_MATERIAL_PARAMETER
const GL_NORMALIZE = 0x0BA1
export GL_NORMALIZE
const GL_CLIP_PLANE0 = 0x3000
export GL_CLIP_PLANE0
const GL_CLIP_PLANE1 = 0x3001
export GL_CLIP_PLANE1
const GL_CLIP_PLANE2 = 0x3002
export GL_CLIP_PLANE2
const GL_CLIP_PLANE3 = 0x3003
export GL_CLIP_PLANE3
const GL_CLIP_PLANE4 = 0x3004
export GL_CLIP_PLANE4
const GL_CLIP_PLANE5 = 0x3005
export GL_CLIP_PLANE5
const GL_ACCUM_RED_BITS = 0x0D58
export GL_ACCUM_RED_BITS
const GL_ACCUM_GREEN_BITS = 0x0D59
export GL_ACCUM_GREEN_BITS
const GL_ACCUM_BLUE_BITS = 0x0D5A
export GL_ACCUM_BLUE_BITS
const GL_ACCUM_ALPHA_BITS = 0x0D5B
export GL_ACCUM_ALPHA_BITS
const GL_ACCUM_CLEAR_VALUE = 0x0B80
export GL_ACCUM_CLEAR_VALUE
const GL_ACCUM = 0x0100
export GL_ACCUM
const GL_ADD = 0x0104
export GL_ADD
const GL_LOAD = 0x0101
export GL_LOAD
const GL_MULT = 0x0103
export GL_MULT
const GL_RETURN = 0x0102
export GL_RETURN
const GL_ALPHA_TEST = 0x0BC0
export GL_ALPHA_TEST
const GL_ALPHA_TEST_REF = 0x0BC2
export GL_ALPHA_TEST_REF
const GL_ALPHA_TEST_FUNC = 0x0BC1
export GL_ALPHA_TEST_FUNC
const GL_BLEND = 0x0BE2
export GL_BLEND
const GL_BLEND_SRC = 0x0BE1
export GL_BLEND_SRC
const GL_BLEND_DST = 0x0BE0
export GL_BLEND_DST
const GL_ZERO = 0x0
export GL_ZERO
const GL_ONE = 0x1
export GL_ONE
const GL_SRC_COLOR = 0x0300
export GL_SRC_COLOR
const GL_ONE_MINUS_SRC_COLOR = 0x0301
export GL_ONE_MINUS_SRC_COLOR
const GL_SRC_ALPHA = 0x0302
export GL_SRC_ALPHA
const GL_ONE_MINUS_SRC_ALPHA = 0x0303
export GL_ONE_MINUS_SRC_ALPHA
const GL_DST_ALPHA = 0x0304
export GL_DST_ALPHA
const GL_ONE_MINUS_DST_ALPHA = 0x0305
export GL_ONE_MINUS_DST_ALPHA
const GL_DST_COLOR = 0x0306
export GL_DST_COLOR
const GL_ONE_MINUS_DST_COLOR = 0x0307
export GL_ONE_MINUS_DST_COLOR
const GL_SRC_ALPHA_SATURATE = 0x0308
export GL_SRC_ALPHA_SATURATE
const GL_FEEDBACK = 0x1C01
export GL_FEEDBACK
const GL_RENDER = 0x1C00
export GL_RENDER
const GL_SELECT = 0x1C02
export GL_SELECT
const GL_2D = 0x0600
export GL_2D
const GL_3D = 0x0601
export GL_3D
const GL_3D_COLOR = 0x0602
export GL_3D_COLOR
const GL_3D_COLOR_TEXTURE = 0x0603
export GL_3D_COLOR_TEXTURE
const GL_4D_COLOR_TEXTURE = 0x0604
export GL_4D_COLOR_TEXTURE
const GL_POINT_TOKEN = 0x0701
export GL_POINT_TOKEN
const GL_LINE_TOKEN = 0x0702
export GL_LINE_TOKEN
const GL_LINE_RESET_TOKEN = 0x0707
export GL_LINE_RESET_TOKEN
const GL_POLYGON_TOKEN = 0x0703
export GL_POLYGON_TOKEN
const GL_BITMAP_TOKEN = 0x0704
export GL_BITMAP_TOKEN
const GL_DRAW_PIXEL_TOKEN = 0x0705
export GL_DRAW_PIXEL_TOKEN
const GL_COPY_PIXEL_TOKEN = 0x0706
export GL_COPY_PIXEL_TOKEN
const GL_PASS_THROUGH_TOKEN = 0x0700
export GL_PASS_THROUGH_TOKEN
const GL_FEEDBACK_BUFFER_POINTER = 0x0DF0
export GL_FEEDBACK_BUFFER_POINTER
const GL_FEEDBACK_BUFFER_SIZE = 0x0DF1
export GL_FEEDBACK_BUFFER_SIZE
const GL_FEEDBACK_BUFFER_TYPE = 0x0DF2
export GL_FEEDBACK_BUFFER_TYPE
const GL_SELECTION_BUFFER_POINTER = 0x0DF3
export GL_SELECTION_BUFFER_POINTER
const GL_SELECTION_BUFFER_SIZE = 0x0DF4
export GL_SELECTION_BUFFER_SIZE
const GL_FOG = 0x0B60
export GL_FOG
const GL_FOG_MODE = 0x0B65
export GL_FOG_MODE
const GL_FOG_DENSITY = 0x0B62
export GL_FOG_DENSITY
const GL_FOG_COLOR = 0x0B66
export GL_FOG_COLOR
const GL_FOG_INDEX = 0x0B61
export GL_FOG_INDEX
const GL_FOG_START = 0x0B63
export GL_FOG_START
const GL_FOG_END = 0x0B64
export GL_FOG_END
const GL_LINEAR = 0x2601
export GL_LINEAR
const GL_EXP = 0x0800
export GL_EXP
const GL_EXP2 = 0x0801
export GL_EXP2
const GL_LOGIC_OP = 0x0BF1
export GL_LOGIC_OP
const GL_INDEX_LOGIC_OP = 0x0BF1
export GL_INDEX_LOGIC_OP
const GL_COLOR_LOGIC_OP = 0x0BF2
export GL_COLOR_LOGIC_OP
const GL_LOGIC_OP_MODE = 0x0BF0
export GL_LOGIC_OP_MODE
const GL_CLEAR = 0x1500
export GL_CLEAR
const GL_SET = 0x150F
export GL_SET
const GL_COPY = 0x1503
export GL_COPY
const GL_COPY_INVERTED = 0x150C
export GL_COPY_INVERTED
const GL_NOOP = 0x1505
export GL_NOOP
const GL_INVERT = 0x150A
export GL_INVERT
const GL_AND = 0x1501
export GL_AND
const GL_NAND = 0x150E
export GL_NAND
const GL_OR = 0x1507
export GL_OR
const GL_NOR = 0x1508
export GL_NOR
const GL_XOR = 0x1506
export GL_XOR
const GL_EQUIV = 0x1509
export GL_EQUIV
const GL_AND_REVERSE = 0x1502
export GL_AND_REVERSE
const GL_AND_INVERTED = 0x1504
export GL_AND_INVERTED
const GL_OR_REVERSE = 0x150B
export GL_OR_REVERSE
const GL_OR_INVERTED = 0x150D
export GL_OR_INVERTED
const GL_STENCIL_BITS = 0x0D57
export GL_STENCIL_BITS
const GL_STENCIL_TEST = 0x0B90
export GL_STENCIL_TEST
const GL_STENCIL_CLEAR_VALUE = 0x0B91
export GL_STENCIL_CLEAR_VALUE
const GL_STENCIL_FUNC = 0x0B92
export GL_STENCIL_FUNC
const GL_STENCIL_VALUE_MASK = 0x0B93
export GL_STENCIL_VALUE_MASK
const GL_STENCIL_FAIL = 0x0B94
export GL_STENCIL_FAIL
const GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95
export GL_STENCIL_PASS_DEPTH_FAIL
const GL_STENCIL_PASS_DEPTH_PASS = 0x0B96
export GL_STENCIL_PASS_DEPTH_PASS
const GL_STENCIL_REF = 0x0B97
export GL_STENCIL_REF
const GL_STENCIL_WRITEMASK = 0x0B98
export GL_STENCIL_WRITEMASK
const GL_STENCIL_INDEX = 0x1901
export GL_STENCIL_INDEX
const GL_KEEP = 0x1E00
export GL_KEEP
const GL_REPLACE = 0x1E01
export GL_REPLACE
const GL_INCR = 0x1E02
export GL_INCR
const GL_DECR = 0x1E03
export GL_DECR
const GL_NONE = 0x0
export GL_NONE
const GL_LEFT = 0x0406
export GL_LEFT
const GL_RIGHT = 0x0407
export GL_RIGHT
const GL_FRONT_LEFT = 0x0400
export GL_FRONT_LEFT
const GL_FRONT_RIGHT = 0x0401
export GL_FRONT_RIGHT
const GL_BACK_LEFT = 0x0402
export GL_BACK_LEFT
const GL_BACK_RIGHT = 0x0403
export GL_BACK_RIGHT
const GL_AUX0 = 0x0409
export GL_AUX0
const GL_AUX1 = 0x040A
export GL_AUX1
const GL_AUX2 = 0x040B
export GL_AUX2
const GL_AUX3 = 0x040C
export GL_AUX3
const GL_COLOR_INDEX = 0x1900
export GL_COLOR_INDEX
const GL_RED = 0x1903
export GL_RED
const GL_GREEN = 0x1904
export GL_GREEN
const GL_BLUE = 0x1905
export GL_BLUE
const GL_ALPHA = 0x1906
export GL_ALPHA
const GL_LUMINANCE = 0x1909
export GL_LUMINANCE
const GL_LUMINANCE_ALPHA = 0x190A
export GL_LUMINANCE_ALPHA
const GL_ALPHA_BITS = 0x0D55
export GL_ALPHA_BITS
const GL_RED_BITS = 0x0D52
export GL_RED_BITS
const GL_GREEN_BITS = 0x0D53
export GL_GREEN_BITS
const GL_BLUE_BITS = 0x0D54
export GL_BLUE_BITS
const GL_INDEX_BITS = 0x0D51
export GL_INDEX_BITS
const GL_SUBPIXEL_BITS = 0x0D50
export GL_SUBPIXEL_BITS
const GL_AUX_BUFFERS = 0x0C00
export GL_AUX_BUFFERS
const GL_READ_BUFFER = 0x0C02
export GL_READ_BUFFER
const GL_DRAW_BUFFER = 0x0C01
export GL_DRAW_BUFFER
const GL_DOUBLEBUFFER = 0x0C32
export GL_DOUBLEBUFFER
const GL_STEREO = 0x0C33
export GL_STEREO
const GL_BITMAP = 0x1A00
export GL_BITMAP
const GL_COLOR = 0x1800
export GL_COLOR
const GL_DEPTH = 0x1801
export GL_DEPTH
const GL_STENCIL = 0x1802
export GL_STENCIL
const GL_DITHER = 0x0BD0
export GL_DITHER
const GL_RGB = 0x1907
export GL_RGB
const GL_RGBA = 0x1908
export GL_RGBA
const GL_MAX_LIST_NESTING = 0x0B31
export GL_MAX_LIST_NESTING
const GL_MAX_EVAL_ORDER = 0x0D30
export GL_MAX_EVAL_ORDER
const GL_MAX_LIGHTS = 0x0D31
export GL_MAX_LIGHTS
const GL_MAX_CLIP_PLANES = 0x0D32
export GL_MAX_CLIP_PLANES
const GL_MAX_TEXTURE_SIZE = 0x0D33
export GL_MAX_TEXTURE_SIZE
const GL_MAX_PIXEL_MAP_TABLE = 0x0D34
export GL_MAX_PIXEL_MAP_TABLE
const GL_MAX_ATTRIB_STACK_DEPTH = 0x0D35
export GL_MAX_ATTRIB_STACK_DEPTH
const GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36
export GL_MAX_MODELVIEW_STACK_DEPTH
const GL_MAX_NAME_STACK_DEPTH = 0x0D37
export GL_MAX_NAME_STACK_DEPTH
const GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38
export GL_MAX_PROJECTION_STACK_DEPTH
const GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39
export GL_MAX_TEXTURE_STACK_DEPTH
const GL_MAX_VIEWPORT_DIMS = 0x0D3A
export GL_MAX_VIEWPORT_DIMS
const GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0x0D3B
export GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
const GL_ATTRIB_STACK_DEPTH = 0x0BB0
export GL_ATTRIB_STACK_DEPTH
const GL_CLIENT_ATTRIB_STACK_DEPTH = 0x0BB1
export GL_CLIENT_ATTRIB_STACK_DEPTH
const GL_COLOR_CLEAR_VALUE = 0x0C22
export GL_COLOR_CLEAR_VALUE
const GL_COLOR_WRITEMASK = 0x0C23
export GL_COLOR_WRITEMASK
const GL_CURRENT_INDEX = 0x0B01
export GL_CURRENT_INDEX
const GL_CURRENT_COLOR = 0x0B00
export GL_CURRENT_COLOR
const GL_CURRENT_NORMAL = 0x0B02
export GL_CURRENT_NORMAL
const GL_CURRENT_RASTER_COLOR = 0x0B04
export GL_CURRENT_RASTER_COLOR
const GL_CURRENT_RASTER_DISTANCE = 0x0B09
export GL_CURRENT_RASTER_DISTANCE
const GL_CURRENT_RASTER_INDEX = 0x0B05
export GL_CURRENT_RASTER_INDEX
const GL_CURRENT_RASTER_POSITION = 0x0B07
export GL_CURRENT_RASTER_POSITION
const GL_CURRENT_RASTER_TEXTURE_COORDS = 0x0B06
export GL_CURRENT_RASTER_TEXTURE_COORDS
const GL_CURRENT_RASTER_POSITION_VALID = 0x0B08
export GL_CURRENT_RASTER_POSITION_VALID
const GL_CURRENT_TEXTURE_COORDS = 0x0B03
export GL_CURRENT_TEXTURE_COORDS
const GL_INDEX_CLEAR_VALUE = 0x0C20
export GL_INDEX_CLEAR_VALUE
const GL_INDEX_MODE = 0x0C30
export GL_INDEX_MODE
const GL_INDEX_WRITEMASK = 0x0C21
export GL_INDEX_WRITEMASK
const GL_MODELVIEW_MATRIX = 0x0BA6
export GL_MODELVIEW_MATRIX
const GL_MODELVIEW_STACK_DEPTH = 0x0BA3
export GL_MODELVIEW_STACK_DEPTH
const GL_NAME_STACK_DEPTH = 0x0D70
export GL_NAME_STACK_DEPTH
const GL_PROJECTION_MATRIX = 0x0BA7
export GL_PROJECTION_MATRIX
const GL_PROJECTION_STACK_DEPTH = 0x0BA4
export GL_PROJECTION_STACK_DEPTH
const GL_RENDER_MODE = 0x0C40
export GL_RENDER_MODE
const GL_RGBA_MODE = 0x0C31
export GL_RGBA_MODE
const GL_TEXTURE_MATRIX = 0x0BA8
export GL_TEXTURE_MATRIX
const GL_TEXTURE_STACK_DEPTH = 0x0BA5
export GL_TEXTURE_STACK_DEPTH
const GL_VIEWPORT = 0x0BA2
export GL_VIEWPORT
const GL_AUTO_NORMAL = 0x0D80
export GL_AUTO_NORMAL
const GL_MAP1_COLOR_4 = 0x0D90
export GL_MAP1_COLOR_4
const GL_MAP1_INDEX = 0x0D91
export GL_MAP1_INDEX
const GL_MAP1_NORMAL = 0x0D92
export GL_MAP1_NORMAL
const GL_MAP1_TEXTURE_COORD_1 = 0x0D93
export GL_MAP1_TEXTURE_COORD_1
const GL_MAP1_TEXTURE_COORD_2 = 0x0D94
export GL_MAP1_TEXTURE_COORD_2
const GL_MAP1_TEXTURE_COORD_3 = 0x0D95
export GL_MAP1_TEXTURE_COORD_3
const GL_MAP1_TEXTURE_COORD_4 = 0x0D96
export GL_MAP1_TEXTURE_COORD_4
const GL_MAP1_VERTEX_3 = 0x0D97
export GL_MAP1_VERTEX_3
const GL_MAP1_VERTEX_4 = 0x0D98
export GL_MAP1_VERTEX_4
const GL_MAP2_COLOR_4 = 0x0DB0
export GL_MAP2_COLOR_4
const GL_MAP2_INDEX = 0x0DB1
export GL_MAP2_INDEX
const GL_MAP2_NORMAL = 0x0DB2
export GL_MAP2_NORMAL
const GL_MAP2_TEXTURE_COORD_1 = 0x0DB3
export GL_MAP2_TEXTURE_COORD_1
const GL_MAP2_TEXTURE_COORD_2 = 0x0DB4
export GL_MAP2_TEXTURE_COORD_2
const GL_MAP2_TEXTURE_COORD_3 = 0x0DB5
export GL_MAP2_TEXTURE_COORD_3
const GL_MAP2_TEXTURE_COORD_4 = 0x0DB6
export GL_MAP2_TEXTURE_COORD_4
const GL_MAP2_VERTEX_3 = 0x0DB7
export GL_MAP2_VERTEX_3
const GL_MAP2_VERTEX_4 = 0x0DB8
export GL_MAP2_VERTEX_4
const GL_MAP1_GRID_DOMAIN = 0x0DD0
export GL_MAP1_GRID_DOMAIN
const GL_MAP1_GRID_SEGMENTS = 0x0DD1
export GL_MAP1_GRID_SEGMENTS
const GL_MAP2_GRID_DOMAIN = 0x0DD2
export GL_MAP2_GRID_DOMAIN
const GL_MAP2_GRID_SEGMENTS = 0x0DD3
export GL_MAP2_GRID_SEGMENTS
const GL_COEFF = 0x0A00
export GL_COEFF
const GL_ORDER = 0x0A01
export GL_ORDER
const GL_DOMAIN = 0x0A02
export GL_DOMAIN
const GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50
export GL_PERSPECTIVE_CORRECTION_HINT
const GL_POINT_SMOOTH_HINT = 0x0C51
export GL_POINT_SMOOTH_HINT
const GL_LINE_SMOOTH_HINT = 0x0C52
export GL_LINE_SMOOTH_HINT
const GL_POLYGON_SMOOTH_HINT = 0x0C53
export GL_POLYGON_SMOOTH_HINT
const GL_FOG_HINT = 0x0C54
export GL_FOG_HINT
const GL_DONT_CARE = 0x1100
export GL_DONT_CARE
const GL_FASTEST = 0x1101
export GL_FASTEST
const GL_NICEST = 0x1102
export GL_NICEST
const GL_SCISSOR_BOX = 0x0C10
export GL_SCISSOR_BOX
const GL_SCISSOR_TEST = 0x0C11
export GL_SCISSOR_TEST
const GL_MAP_COLOR = 0x0D10
export GL_MAP_COLOR
const GL_MAP_STENCIL = 0x0D11
export GL_MAP_STENCIL
const GL_INDEX_SHIFT = 0x0D12
export GL_INDEX_SHIFT
const GL_INDEX_OFFSET = 0x0D13
export GL_INDEX_OFFSET
const GL_RED_SCALE = 0x0D14
export GL_RED_SCALE
const GL_RED_BIAS = 0x0D15
export GL_RED_BIAS
const GL_GREEN_SCALE = 0x0D18
export GL_GREEN_SCALE
const GL_GREEN_BIAS = 0x0D19
export GL_GREEN_BIAS
const GL_BLUE_SCALE = 0x0D1A
export GL_BLUE_SCALE
const GL_BLUE_BIAS = 0x0D1B
export GL_BLUE_BIAS
const GL_ALPHA_SCALE = 0x0D1C
export GL_ALPHA_SCALE
const GL_ALPHA_BIAS = 0x0D1D
export GL_ALPHA_BIAS
const GL_DEPTH_SCALE = 0x0D1E
export GL_DEPTH_SCALE
const GL_DEPTH_BIAS = 0x0D1F
export GL_DEPTH_BIAS
const GL_PIXEL_MAP_S_TO_S_SIZE = 0x0CB1
export GL_PIXEL_MAP_S_TO_S_SIZE
const GL_PIXEL_MAP_I_TO_I_SIZE = 0x0CB0
export GL_PIXEL_MAP_I_TO_I_SIZE
const GL_PIXEL_MAP_I_TO_R_SIZE = 0x0CB2
export GL_PIXEL_MAP_I_TO_R_SIZE
const GL_PIXEL_MAP_I_TO_G_SIZE = 0x0CB3
export GL_PIXEL_MAP_I_TO_G_SIZE
const GL_PIXEL_MAP_I_TO_B_SIZE = 0x0CB4
export GL_PIXEL_MAP_I_TO_B_SIZE
const GL_PIXEL_MAP_I_TO_A_SIZE = 0x0CB5
export GL_PIXEL_MAP_I_TO_A_SIZE
const GL_PIXEL_MAP_R_TO_R_SIZE = 0x0CB6
export GL_PIXEL_MAP_R_TO_R_SIZE
const GL_PIXEL_MAP_G_TO_G_SIZE = 0x0CB7
export GL_PIXEL_MAP_G_TO_G_SIZE
const GL_PIXEL_MAP_B_TO_B_SIZE = 0x0CB8
export GL_PIXEL_MAP_B_TO_B_SIZE
const GL_PIXEL_MAP_A_TO_A_SIZE = 0x0CB9
export GL_PIXEL_MAP_A_TO_A_SIZE
const GL_PIXEL_MAP_S_TO_S = 0x0C71
export GL_PIXEL_MAP_S_TO_S
const GL_PIXEL_MAP_I_TO_I = 0x0C70
export GL_PIXEL_MAP_I_TO_I
const GL_PIXEL_MAP_I_TO_R = 0x0C72
export GL_PIXEL_MAP_I_TO_R
const GL_PIXEL_MAP_I_TO_G = 0x0C73
export GL_PIXEL_MAP_I_TO_G
const GL_PIXEL_MAP_I_TO_B = 0x0C74
export GL_PIXEL_MAP_I_TO_B
const GL_PIXEL_MAP_I_TO_A = 0x0C75
export GL_PIXEL_MAP_I_TO_A
const GL_PIXEL_MAP_R_TO_R = 0x0C76
export GL_PIXEL_MAP_R_TO_R
const GL_PIXEL_MAP_G_TO_G = 0x0C77
export GL_PIXEL_MAP_G_TO_G
const GL_PIXEL_MAP_B_TO_B = 0x0C78
export GL_PIXEL_MAP_B_TO_B
const GL_PIXEL_MAP_A_TO_A = 0x0C79
export GL_PIXEL_MAP_A_TO_A
const GL_PACK_ALIGNMENT = 0x0D05
export GL_PACK_ALIGNMENT
const GL_PACK_LSB_FIRST = 0x0D01
export GL_PACK_LSB_FIRST
const GL_PACK_ROW_LENGTH = 0x0D02
export GL_PACK_ROW_LENGTH
const GL_PACK_SKIP_PIXELS = 0x0D04
export GL_PACK_SKIP_PIXELS
const GL_PACK_SKIP_ROWS = 0x0D03
export GL_PACK_SKIP_ROWS
const GL_PACK_SWAP_BYTES = 0x0D00
export GL_PACK_SWAP_BYTES
const GL_UNPACK_ALIGNMENT = 0x0CF5
export GL_UNPACK_ALIGNMENT
const GL_UNPACK_LSB_FIRST = 0x0CF1
export GL_UNPACK_LSB_FIRST
const GL_UNPACK_ROW_LENGTH = 0x0CF2
export GL_UNPACK_ROW_LENGTH
const GL_UNPACK_SKIP_PIXELS = 0x0CF4
export GL_UNPACK_SKIP_PIXELS
const GL_UNPACK_SKIP_ROWS = 0x0CF3
export GL_UNPACK_SKIP_ROWS
const GL_UNPACK_SWAP_BYTES = 0x0CF0
export GL_UNPACK_SWAP_BYTES
const GL_ZOOM_X = 0x0D16
export GL_ZOOM_X
const GL_ZOOM_Y = 0x0D17
export GL_ZOOM_Y
const GL_TEXTURE_ENV = 0x2300
export GL_TEXTURE_ENV
const GL_TEXTURE_ENV_MODE = 0x2200
export GL_TEXTURE_ENV_MODE
const GL_TEXTURE_1D = 0x0DE0
export GL_TEXTURE_1D
const GL_TEXTURE_2D = 0x0DE1
export GL_TEXTURE_2D
const GL_TEXTURE_WRAP_S = 0x2802
export GL_TEXTURE_WRAP_S
const GL_TEXTURE_WRAP_T = 0x2803
export GL_TEXTURE_WRAP_T
const GL_TEXTURE_MAG_FILTER = 0x2800
export GL_TEXTURE_MAG_FILTER
const GL_TEXTURE_MIN_FILTER = 0x2801
export GL_TEXTURE_MIN_FILTER
const GL_TEXTURE_ENV_COLOR = 0x2201
export GL_TEXTURE_ENV_COLOR
const GL_TEXTURE_GEN_S = 0x0C60
export GL_TEXTURE_GEN_S
const GL_TEXTURE_GEN_T = 0x0C61
export GL_TEXTURE_GEN_T
const GL_TEXTURE_GEN_R = 0x0C62
export GL_TEXTURE_GEN_R
const GL_TEXTURE_GEN_Q = 0x0C63
export GL_TEXTURE_GEN_Q
const GL_TEXTURE_GEN_MODE = 0x2500
export GL_TEXTURE_GEN_MODE
const GL_TEXTURE_BORDER_COLOR = 0x1004
export GL_TEXTURE_BORDER_COLOR
const GL_TEXTURE_WIDTH = 0x1000
export GL_TEXTURE_WIDTH
const GL_TEXTURE_HEIGHT = 0x1001
export GL_TEXTURE_HEIGHT
const GL_TEXTURE_BORDER = 0x1005
export GL_TEXTURE_BORDER
const GL_TEXTURE_COMPONENTS = 0x1003
export GL_TEXTURE_COMPONENTS
const GL_TEXTURE_RED_SIZE = 0x805C
export GL_TEXTURE_RED_SIZE
const GL_TEXTURE_GREEN_SIZE = 0x805D
export GL_TEXTURE_GREEN_SIZE
const GL_TEXTURE_BLUE_SIZE = 0x805E
export GL_TEXTURE_BLUE_SIZE
const GL_TEXTURE_ALPHA_SIZE = 0x805F
export GL_TEXTURE_ALPHA_SIZE
const GL_TEXTURE_LUMINANCE_SIZE = 0x8060
export GL_TEXTURE_LUMINANCE_SIZE
const GL_TEXTURE_INTENSITY_SIZE = 0x8061
export GL_TEXTURE_INTENSITY_SIZE
const GL_NEAREST_MIPMAP_NEAREST = 0x2700
export GL_NEAREST_MIPMAP_NEAREST
const GL_NEAREST_MIPMAP_LINEAR = 0x2702
export GL_NEAREST_MIPMAP_LINEAR
const GL_LINEAR_MIPMAP_NEAREST = 0x2701
export GL_LINEAR_MIPMAP_NEAREST
const GL_LINEAR_MIPMAP_LINEAR = 0x2703
export GL_LINEAR_MIPMAP_LINEAR
const GL_OBJECT_LINEAR = 0x2401
export GL_OBJECT_LINEAR
const GL_OBJECT_PLANE = 0x2501
export GL_OBJECT_PLANE
const GL_EYE_LINEAR = 0x2400
export GL_EYE_LINEAR
const GL_EYE_PLANE = 0x2502
export GL_EYE_PLANE
const GL_SPHERE_MAP = 0x2402
export GL_SPHERE_MAP
const GL_DECAL = 0x2101
export GL_DECAL
const GL_MODULATE = 0x2100
export GL_MODULATE
const GL_NEAREST = 0x2600
export GL_NEAREST
const GL_REPEAT = 0x2901
export GL_REPEAT
const GL_CLAMP = 0x2900
export GL_CLAMP
const GL_S = 0x2000
export GL_S
const GL_T = 0x2001
export GL_T
const GL_R = 0x2002
export GL_R
const GL_Q = 0x2003
export GL_Q
const GL_VENDOR = 0x1F00
export GL_VENDOR
const GL_RENDERER = 0x1F01
export GL_RENDERER
const GL_VERSION = 0x1F02
export GL_VERSION
const GL_EXTENSIONS = 0x1F03
export GL_EXTENSIONS
const GL_NO_ERROR = 0x0
export GL_NO_ERROR
const GL_INVALID_ENUM = 0x0500
export GL_INVALID_ENUM
const GL_INVALID_VALUE = 0x0501
export GL_INVALID_VALUE
const GL_INVALID_OPERATION = 0x0502
export GL_INVALID_OPERATION
const GL_STACK_OVERFLOW = 0x0503
export GL_STACK_OVERFLOW
const GL_STACK_UNDERFLOW = 0x0504
export GL_STACK_UNDERFLOW
const GL_OUT_OF_MEMORY = 0x0505
export GL_OUT_OF_MEMORY
const GL_CURRENT_BIT = 0x00000001
export GL_CURRENT_BIT
const GL_POINT_BIT = 0x00000002
export GL_POINT_BIT
const GL_LINE_BIT = 0x00000004
export GL_LINE_BIT
const GL_POLYGON_BIT = 0x00000008
export GL_POLYGON_BIT
const GL_POLYGON_STIPPLE_BIT = 0x00000010
export GL_POLYGON_STIPPLE_BIT
const GL_PIXEL_MODE_BIT = 0x00000020
export GL_PIXEL_MODE_BIT
const GL_LIGHTING_BIT = 0x00000040
export GL_LIGHTING_BIT
const GL_FOG_BIT = 0x00000080
export GL_FOG_BIT
const GL_DEPTH_BUFFER_BIT = 0x00000100
export GL_DEPTH_BUFFER_BIT
const GL_ACCUM_BUFFER_BIT = 0x00000200
export GL_ACCUM_BUFFER_BIT
const GL_STENCIL_BUFFER_BIT = 0x00000400
export GL_STENCIL_BUFFER_BIT
const GL_VIEWPORT_BIT = 0x00000800
export GL_VIEWPORT_BIT
const GL_TRANSFORM_BIT = 0x00001000
export GL_TRANSFORM_BIT
const GL_ENABLE_BIT = 0x00002000
export GL_ENABLE_BIT
const GL_COLOR_BUFFER_BIT = 0x00004000
export GL_COLOR_BUFFER_BIT
const GL_HINT_BIT = 0x00008000
export GL_HINT_BIT
const GL_EVAL_BIT = 0x00010000
export GL_EVAL_BIT
const GL_LIST_BIT = 0x00020000
export GL_LIST_BIT
const GL_TEXTURE_BIT = 0x00040000
export GL_TEXTURE_BIT
const GL_SCISSOR_BIT = 0x00080000
export GL_SCISSOR_BIT
const GL_ALL_ATTRIB_BITS = 0x000FFFFF
export GL_ALL_ATTRIB_BITS
const GL_PROXY_TEXTURE_1D = 0x8063
export GL_PROXY_TEXTURE_1D
const GL_PROXY_TEXTURE_2D = 0x8064
export GL_PROXY_TEXTURE_2D
const GL_TEXTURE_PRIORITY = 0x8066
export GL_TEXTURE_PRIORITY
const GL_TEXTURE_RESIDENT = 0x8067
export GL_TEXTURE_RESIDENT
const GL_TEXTURE_BINDING_1D = 0x8068
export GL_TEXTURE_BINDING_1D
const GL_TEXTURE_BINDING_2D = 0x8069
export GL_TEXTURE_BINDING_2D
const GL_TEXTURE_INTERNAL_FORMAT = 0x1003
export GL_TEXTURE_INTERNAL_FORMAT
const GL_ALPHA4 = 0x803B
export GL_ALPHA4
const GL_ALPHA8 = 0x803C
export GL_ALPHA8
const GL_ALPHA12 = 0x803D
export GL_ALPHA12
const GL_ALPHA16 = 0x803E
export GL_ALPHA16
const GL_LUMINANCE4 = 0x803F
export GL_LUMINANCE4
const GL_LUMINANCE8 = 0x8040
export GL_LUMINANCE8
const GL_LUMINANCE12 = 0x8041
export GL_LUMINANCE12
const GL_LUMINANCE16 = 0x8042
export GL_LUMINANCE16
const GL_LUMINANCE4_ALPHA4 = 0x8043
export GL_LUMINANCE4_ALPHA4
const GL_LUMINANCE6_ALPHA2 = 0x8044
export GL_LUMINANCE6_ALPHA2
const GL_LUMINANCE8_ALPHA8 = 0x8045
export GL_LUMINANCE8_ALPHA8
const GL_LUMINANCE12_ALPHA4 = 0x8046
export GL_LUMINANCE12_ALPHA4
const GL_LUMINANCE12_ALPHA12 = 0x8047
export GL_LUMINANCE12_ALPHA12
const GL_LUMINANCE16_ALPHA16 = 0x8048
export GL_LUMINANCE16_ALPHA16
const GL_INTENSITY = 0x8049
export GL_INTENSITY
const GL_INTENSITY4 = 0x804A
export GL_INTENSITY4
const GL_INTENSITY8 = 0x804B
export GL_INTENSITY8
const GL_INTENSITY12 = 0x804C
export GL_INTENSITY12
const GL_INTENSITY16 = 0x804D
export GL_INTENSITY16
const GL_R3_G3_B2 = 0x2A10
export GL_R3_G3_B2
const GL_RGB4 = 0x804F
export GL_RGB4
const GL_RGB5 = 0x8050
export GL_RGB5
const GL_RGB8 = 0x8051
export GL_RGB8
const GL_RGB10 = 0x8052
export GL_RGB10
const GL_RGB12 = 0x8053
export GL_RGB12
const GL_RGB16 = 0x8054
export GL_RGB16
const GL_RGBA2 = 0x8055
export GL_RGBA2
const GL_RGBA4 = 0x8056
export GL_RGBA4
const GL_RGB5_A1 = 0x8057
export GL_RGB5_A1
const GL_RGBA8 = 0x8058
export GL_RGBA8
const GL_RGB10_A2 = 0x8059
export GL_RGB10_A2
const GL_RGBA12 = 0x805A
export GL_RGBA12
const GL_RGBA16 = 0x805B
export GL_RGBA16
const GL_CLIENT_PIXEL_STORE_BIT = 0x00000001
export GL_CLIENT_PIXEL_STORE_BIT
const GL_CLIENT_VERTEX_ARRAY_BIT = 0x00000002
export GL_CLIENT_VERTEX_ARRAY_BIT
const GL_ALL_CLIENT_ATTRIB_BITS = 0xFFFFFFFF
export GL_ALL_CLIENT_ATTRIB_BITS
const GL_CLIENT_ALL_ATTRIB_BITS = 0xFFFFFFFF
export GL_CLIENT_ALL_ATTRIB_BITS
const GL_RESCALE_NORMAL = 0x803A
export GL_RESCALE_NORMAL
const GL_CLAMP_TO_EDGE = 0x812F
export GL_CLAMP_TO_EDGE
const GL_MAX_ELEMENTS_VERTICES = 0x80E8
export GL_MAX_ELEMENTS_VERTICES
const GL_MAX_ELEMENTS_INDICES = 0x80E9
export GL_MAX_ELEMENTS_INDICES
const GL_BGR = 0x80E0
export GL_BGR
const GL_BGRA = 0x80E1
export GL_BGRA
const GL_UNSIGNED_BYTE_3_3_2 = 0x8032
export GL_UNSIGNED_BYTE_3_3_2
const GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362
export GL_UNSIGNED_BYTE_2_3_3_REV
const GL_UNSIGNED_SHORT_5_6_5 = 0x8363
export GL_UNSIGNED_SHORT_5_6_5
const GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364
export GL_UNSIGNED_SHORT_5_6_5_REV
const GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033
export GL_UNSIGNED_SHORT_4_4_4_4
const GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365
export GL_UNSIGNED_SHORT_4_4_4_4_REV
const GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034
export GL_UNSIGNED_SHORT_5_5_5_1
const GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366
export GL_UNSIGNED_SHORT_1_5_5_5_REV
const GL_UNSIGNED_INT_8_8_8_8 = 0x8035
export GL_UNSIGNED_INT_8_8_8_8
const GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367
export GL_UNSIGNED_INT_8_8_8_8_REV
const GL_UNSIGNED_INT_10_10_10_2 = 0x8036
export GL_UNSIGNED_INT_10_10_10_2
const GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368
export GL_UNSIGNED_INT_2_10_10_10_REV
const GL_LIGHT_MODEL_COLOR_CONTROL = 0x81F8
export GL_LIGHT_MODEL_COLOR_CONTROL
const GL_SINGLE_COLOR = 0x81F9
export GL_SINGLE_COLOR
const GL_SEPARATE_SPECULAR_COLOR = 0x81FA
export GL_SEPARATE_SPECULAR_COLOR
const GL_TEXTURE_MIN_LOD = 0x813A
export GL_TEXTURE_MIN_LOD
const GL_TEXTURE_MAX_LOD = 0x813B
export GL_TEXTURE_MAX_LOD
const GL_TEXTURE_BASE_LEVEL = 0x813C
export GL_TEXTURE_BASE_LEVEL
const GL_TEXTURE_MAX_LEVEL = 0x813D
export GL_TEXTURE_MAX_LEVEL
const GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12
export GL_SMOOTH_POINT_SIZE_RANGE
const GL_SMOOTH_POINT_SIZE_GRANULARITY = 0x0B13
export GL_SMOOTH_POINT_SIZE_GRANULARITY
const GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22
export GL_SMOOTH_LINE_WIDTH_RANGE
const GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0x0B23
export GL_SMOOTH_LINE_WIDTH_GRANULARITY
const GL_ALIASED_POINT_SIZE_RANGE = 0x846D
export GL_ALIASED_POINT_SIZE_RANGE
const GL_ALIASED_LINE_WIDTH_RANGE = 0x846E
export GL_ALIASED_LINE_WIDTH_RANGE
const GL_PACK_SKIP_IMAGES = 0x806B
export GL_PACK_SKIP_IMAGES
const GL_PACK_IMAGE_HEIGHT = 0x806C
export GL_PACK_IMAGE_HEIGHT
const GL_UNPACK_SKIP_IMAGES = 0x806D
export GL_UNPACK_SKIP_IMAGES
const GL_UNPACK_IMAGE_HEIGHT = 0x806E
export GL_UNPACK_IMAGE_HEIGHT
const GL_TEXTURE_3D = 0x806F
export GL_TEXTURE_3D
const GL_PROXY_TEXTURE_3D = 0x8070
export GL_PROXY_TEXTURE_3D
const GL_TEXTURE_DEPTH = 0x8071
export GL_TEXTURE_DEPTH
const GL_TEXTURE_WRAP_R = 0x8072
export GL_TEXTURE_WRAP_R
const GL_MAX_3D_TEXTURE_SIZE = 0x8073
export GL_MAX_3D_TEXTURE_SIZE
const GL_TEXTURE_BINDING_3D = 0x806A
export GL_TEXTURE_BINDING_3D
const GL_CONSTANT_COLOR = 0x8001
export GL_CONSTANT_COLOR
const GL_ONE_MINUS_CONSTANT_COLOR = 0x8002
export GL_ONE_MINUS_CONSTANT_COLOR
const GL_CONSTANT_ALPHA = 0x8003
export GL_CONSTANT_ALPHA
const GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004
export GL_ONE_MINUS_CONSTANT_ALPHA
const GL_COLOR_TABLE = 0x80D0
export GL_COLOR_TABLE
const GL_POST_CONVOLUTION_COLOR_TABLE = 0x80D1
export GL_POST_CONVOLUTION_COLOR_TABLE
const GL_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D2
export GL_POST_COLOR_MATRIX_COLOR_TABLE
const GL_PROXY_COLOR_TABLE = 0x80D3
export GL_PROXY_COLOR_TABLE
const GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = 0x80D4
export GL_PROXY_POST_CONVOLUTION_COLOR_TABLE
const GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D5
export GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE
const GL_COLOR_TABLE_SCALE = 0x80D6
export GL_COLOR_TABLE_SCALE
const GL_COLOR_TABLE_BIAS = 0x80D7
export GL_COLOR_TABLE_BIAS
const GL_COLOR_TABLE_FORMAT = 0x80D8
export GL_COLOR_TABLE_FORMAT
const GL_COLOR_TABLE_WIDTH = 0x80D9
export GL_COLOR_TABLE_WIDTH
const GL_COLOR_TABLE_RED_SIZE = 0x80DA
export GL_COLOR_TABLE_RED_SIZE
const GL_COLOR_TABLE_GREEN_SIZE = 0x80DB
export GL_COLOR_TABLE_GREEN_SIZE
const GL_COLOR_TABLE_BLUE_SIZE = 0x80DC
export GL_COLOR_TABLE_BLUE_SIZE
const GL_COLOR_TABLE_ALPHA_SIZE = 0x80DD
export GL_COLOR_TABLE_ALPHA_SIZE
const GL_COLOR_TABLE_LUMINANCE_SIZE = 0x80DE
export GL_COLOR_TABLE_LUMINANCE_SIZE
const GL_COLOR_TABLE_INTENSITY_SIZE = 0x80DF
export GL_COLOR_TABLE_INTENSITY_SIZE
const GL_CONVOLUTION_1D = 0x8010
export GL_CONVOLUTION_1D
const GL_CONVOLUTION_2D = 0x8011
export GL_CONVOLUTION_2D
const GL_SEPARABLE_2D = 0x8012
export GL_SEPARABLE_2D
const GL_CONVOLUTION_BORDER_MODE = 0x8013
export GL_CONVOLUTION_BORDER_MODE
const GL_CONVOLUTION_FILTER_SCALE = 0x8014
export GL_CONVOLUTION_FILTER_SCALE
const GL_CONVOLUTION_FILTER_BIAS = 0x8015
export GL_CONVOLUTION_FILTER_BIAS
const GL_REDUCE = 0x8016
export GL_REDUCE
const GL_CONVOLUTION_FORMAT = 0x8017
export GL_CONVOLUTION_FORMAT
const GL_CONVOLUTION_WIDTH = 0x8018
export GL_CONVOLUTION_WIDTH
const GL_CONVOLUTION_HEIGHT = 0x8019
export GL_CONVOLUTION_HEIGHT
const GL_MAX_CONVOLUTION_WIDTH = 0x801A
export GL_MAX_CONVOLUTION_WIDTH
const GL_MAX_CONVOLUTION_HEIGHT = 0x801B
export GL_MAX_CONVOLUTION_HEIGHT
const GL_POST_CONVOLUTION_RED_SCALE = 0x801C
export GL_POST_CONVOLUTION_RED_SCALE
const GL_POST_CONVOLUTION_GREEN_SCALE = 0x801D
export GL_POST_CONVOLUTION_GREEN_SCALE
const GL_POST_CONVOLUTION_BLUE_SCALE = 0x801E
export GL_POST_CONVOLUTION_BLUE_SCALE
const GL_POST_CONVOLUTION_ALPHA_SCALE = 0x801F
export GL_POST_CONVOLUTION_ALPHA_SCALE
const GL_POST_CONVOLUTION_RED_BIAS = 0x8020
export GL_POST_CONVOLUTION_RED_BIAS
const GL_POST_CONVOLUTION_GREEN_BIAS = 0x8021
export GL_POST_CONVOLUTION_GREEN_BIAS
const GL_POST_CONVOLUTION_BLUE_BIAS = 0x8022
export GL_POST_CONVOLUTION_BLUE_BIAS
const GL_POST_CONVOLUTION_ALPHA_BIAS = 0x8023
export GL_POST_CONVOLUTION_ALPHA_BIAS
const GL_CONSTANT_BORDER = 0x8151
export GL_CONSTANT_BORDER
const GL_REPLICATE_BORDER = 0x8153
export GL_REPLICATE_BORDER
const GL_CONVOLUTION_BORDER_COLOR = 0x8154
export GL_CONVOLUTION_BORDER_COLOR
const GL_COLOR_MATRIX = 0x80B1
export GL_COLOR_MATRIX
const GL_COLOR_MATRIX_STACK_DEPTH = 0x80B2
export GL_COLOR_MATRIX_STACK_DEPTH
const GL_MAX_COLOR_MATRIX_STACK_DEPTH = 0x80B3
export GL_MAX_COLOR_MATRIX_STACK_DEPTH
const GL_POST_COLOR_MATRIX_RED_SCALE = 0x80B4
export GL_POST_COLOR_MATRIX_RED_SCALE
const GL_POST_COLOR_MATRIX_GREEN_SCALE = 0x80B5
export GL_POST_COLOR_MATRIX_GREEN_SCALE
const GL_POST_COLOR_MATRIX_BLUE_SCALE = 0x80B6
export GL_POST_COLOR_MATRIX_BLUE_SCALE
const GL_POST_COLOR_MATRIX_ALPHA_SCALE = 0x80B7
export GL_POST_COLOR_MATRIX_ALPHA_SCALE
const GL_POST_COLOR_MATRIX_RED_BIAS = 0x80B8
export GL_POST_COLOR_MATRIX_RED_BIAS
const GL_POST_COLOR_MATRIX_GREEN_BIAS = 0x80B9
export GL_POST_COLOR_MATRIX_GREEN_BIAS
const GL_POST_COLOR_MATRIX_BLUE_BIAS = 0x80BA
export GL_POST_COLOR_MATRIX_BLUE_BIAS
const GL_POST_COLOR_MATRIX_ALPHA_BIAS = 0x80BB
export GL_POST_COLOR_MATRIX_ALPHA_BIAS
const GL_HISTOGRAM = 0x8024
export GL_HISTOGRAM
const GL_PROXY_HISTOGRAM = 0x8025
export GL_PROXY_HISTOGRAM
const GL_HISTOGRAM_WIDTH = 0x8026
export GL_HISTOGRAM_WIDTH
const GL_HISTOGRAM_FORMAT = 0x8027
export GL_HISTOGRAM_FORMAT
const GL_HISTOGRAM_RED_SIZE = 0x8028
export GL_HISTOGRAM_RED_SIZE
const GL_HISTOGRAM_GREEN_SIZE = 0x8029
export GL_HISTOGRAM_GREEN_SIZE
const GL_HISTOGRAM_BLUE_SIZE = 0x802A
export GL_HISTOGRAM_BLUE_SIZE
const GL_HISTOGRAM_ALPHA_SIZE = 0x802B
export GL_HISTOGRAM_ALPHA_SIZE
const GL_HISTOGRAM_LUMINANCE_SIZE = 0x802C
export GL_HISTOGRAM_LUMINANCE_SIZE
const GL_HISTOGRAM_SINK = 0x802D
export GL_HISTOGRAM_SINK
const GL_MINMAX = 0x802E
export GL_MINMAX
const GL_MINMAX_FORMAT = 0x802F
export GL_MINMAX_FORMAT
const GL_MINMAX_SINK = 0x8030
export GL_MINMAX_SINK
const GL_TABLE_TOO_LARGE = 0x8031
export GL_TABLE_TOO_LARGE
const GL_BLEND_EQUATION = 0x8009
export GL_BLEND_EQUATION
const GL_MIN = 0x8007
export GL_MIN
const GL_MAX = 0x8008
export GL_MAX
const GL_FUNC_ADD = 0x8006
export GL_FUNC_ADD
const GL_FUNC_SUBTRACT = 0x800A
export GL_FUNC_SUBTRACT
const GL_FUNC_REVERSE_SUBTRACT = 0x800B
export GL_FUNC_REVERSE_SUBTRACT
const GL_BLEND_COLOR = 0x8005
export GL_BLEND_COLOR
const GL_TEXTURE0 = 0x84C0
export GL_TEXTURE0
const GL_TEXTURE1 = 0x84C1
export GL_TEXTURE1
const GL_TEXTURE2 = 0x84C2
export GL_TEXTURE2
const GL_TEXTURE3 = 0x84C3
export GL_TEXTURE3
const GL_TEXTURE4 = 0x84C4
export GL_TEXTURE4
const GL_TEXTURE5 = 0x84C5
export GL_TEXTURE5
const GL_TEXTURE6 = 0x84C6
export GL_TEXTURE6
const GL_TEXTURE7 = 0x84C7
export GL_TEXTURE7
const GL_TEXTURE8 = 0x84C8
export GL_TEXTURE8
const GL_TEXTURE9 = 0x84C9
export GL_TEXTURE9
const GL_TEXTURE10 = 0x84CA
export GL_TEXTURE10
const GL_TEXTURE11 = 0x84CB
export GL_TEXTURE11
const GL_TEXTURE12 = 0x84CC
export GL_TEXTURE12
const GL_TEXTURE13 = 0x84CD
export GL_TEXTURE13
const GL_TEXTURE14 = 0x84CE
export GL_TEXTURE14
const GL_TEXTURE15 = 0x84CF
export GL_TEXTURE15
const GL_TEXTURE16 = 0x84D0
export GL_TEXTURE16
const GL_TEXTURE17 = 0x84D1
export GL_TEXTURE17
const GL_TEXTURE18 = 0x84D2
export GL_TEXTURE18
const GL_TEXTURE19 = 0x84D3
export GL_TEXTURE19
const GL_TEXTURE20 = 0x84D4
export GL_TEXTURE20
const GL_TEXTURE21 = 0x84D5
export GL_TEXTURE21
const GL_TEXTURE22 = 0x84D6
export GL_TEXTURE22
const GL_TEXTURE23 = 0x84D7
export GL_TEXTURE23
const GL_TEXTURE24 = 0x84D8
export GL_TEXTURE24
const GL_TEXTURE25 = 0x84D9
export GL_TEXTURE25
const GL_TEXTURE26 = 0x84DA
export GL_TEXTURE26
const GL_TEXTURE27 = 0x84DB
export GL_TEXTURE27
const GL_TEXTURE28 = 0x84DC
export GL_TEXTURE28
const GL_TEXTURE29 = 0x84DD
export GL_TEXTURE29
const GL_TEXTURE30 = 0x84DE
export GL_TEXTURE30
const GL_TEXTURE31 = 0x84DF
export GL_TEXTURE31
const GL_ACTIVE_TEXTURE = 0x84E0
export GL_ACTIVE_TEXTURE
const GL_CLIENT_ACTIVE_TEXTURE = 0x84E1
export GL_CLIENT_ACTIVE_TEXTURE
const GL_MAX_TEXTURE_UNITS = 0x84E2
export GL_MAX_TEXTURE_UNITS
const GL_NORMAL_MAP = 0x8511
export GL_NORMAL_MAP
const GL_REFLECTION_MAP = 0x8512
export GL_REFLECTION_MAP
const GL_TEXTURE_CUBE_MAP = 0x8513
export GL_TEXTURE_CUBE_MAP
const GL_TEXTURE_BINDING_CUBE_MAP = 0x8514
export GL_TEXTURE_BINDING_CUBE_MAP
const GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515
export GL_TEXTURE_CUBE_MAP_POSITIVE_X
const GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516
export GL_TEXTURE_CUBE_MAP_NEGATIVE_X
const GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517
export GL_TEXTURE_CUBE_MAP_POSITIVE_Y
const GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518
export GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
const GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519
export GL_TEXTURE_CUBE_MAP_POSITIVE_Z
const GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A
export GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
const GL_PROXY_TEXTURE_CUBE_MAP = 0x851B
export GL_PROXY_TEXTURE_CUBE_MAP
const GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C
export GL_MAX_CUBE_MAP_TEXTURE_SIZE
const GL_COMPRESSED_ALPHA = 0x84E9
export GL_COMPRESSED_ALPHA
const GL_COMPRESSED_LUMINANCE = 0x84EA
export GL_COMPRESSED_LUMINANCE
const GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB
export GL_COMPRESSED_LUMINANCE_ALPHA
const GL_COMPRESSED_INTENSITY = 0x84EC
export GL_COMPRESSED_INTENSITY
const GL_COMPRESSED_RGB = 0x84ED
export GL_COMPRESSED_RGB
const GL_COMPRESSED_RGBA = 0x84EE
export GL_COMPRESSED_RGBA
const GL_TEXTURE_COMPRESSION_HINT = 0x84EF
export GL_TEXTURE_COMPRESSION_HINT
const GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0
export GL_TEXTURE_COMPRESSED_IMAGE_SIZE
const GL_TEXTURE_COMPRESSED = 0x86A1
export GL_TEXTURE_COMPRESSED
const GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2
export GL_NUM_COMPRESSED_TEXTURE_FORMATS
const GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3
export GL_COMPRESSED_TEXTURE_FORMATS
const GL_MULTISAMPLE = 0x809D
export GL_MULTISAMPLE
const GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E
export GL_SAMPLE_ALPHA_TO_COVERAGE
const GL_SAMPLE_ALPHA_TO_ONE = 0x809F
export GL_SAMPLE_ALPHA_TO_ONE
const GL_SAMPLE_COVERAGE = 0x80A0
export GL_SAMPLE_COVERAGE
const GL_SAMPLE_BUFFERS = 0x80A8
export GL_SAMPLE_BUFFERS
const GL_SAMPLES = 0x80A9
export GL_SAMPLES
const GL_SAMPLE_COVERAGE_VALUE = 0x80AA
export GL_SAMPLE_COVERAGE_VALUE
const GL_SAMPLE_COVERAGE_INVERT = 0x80AB
export GL_SAMPLE_COVERAGE_INVERT
const GL_MULTISAMPLE_BIT = 0x20000000
export GL_MULTISAMPLE_BIT
const GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3
export GL_TRANSPOSE_MODELVIEW_MATRIX
const GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4
export GL_TRANSPOSE_PROJECTION_MATRIX
const GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5
export GL_TRANSPOSE_TEXTURE_MATRIX
const GL_TRANSPOSE_COLOR_MATRIX = 0x84E6
export GL_TRANSPOSE_COLOR_MATRIX
const GL_COMBINE = 0x8570
export GL_COMBINE
const GL_COMBINE_RGB = 0x8571
export GL_COMBINE_RGB
const GL_COMBINE_ALPHA = 0x8572
export GL_COMBINE_ALPHA
const GL_SOURCE0_RGB = 0x8580
export GL_SOURCE0_RGB
const GL_SOURCE1_RGB = 0x8581
export GL_SOURCE1_RGB
const GL_SOURCE2_RGB = 0x8582
export GL_SOURCE2_RGB
const GL_SOURCE0_ALPHA = 0x8588
export GL_SOURCE0_ALPHA
const GL_SOURCE1_ALPHA = 0x8589
export GL_SOURCE1_ALPHA
const GL_SOURCE2_ALPHA = 0x858A
export GL_SOURCE2_ALPHA
const GL_OPERAND0_RGB = 0x8590
export GL_OPERAND0_RGB
const GL_OPERAND1_RGB = 0x8591
export GL_OPERAND1_RGB
const GL_OPERAND2_RGB = 0x8592
export GL_OPERAND2_RGB
const GL_OPERAND0_ALPHA = 0x8598
export GL_OPERAND0_ALPHA
const GL_OPERAND1_ALPHA = 0x8599
export GL_OPERAND1_ALPHA
const GL_OPERAND2_ALPHA = 0x859A
export GL_OPERAND2_ALPHA
const GL_RGB_SCALE = 0x8573
export GL_RGB_SCALE
const GL_ADD_SIGNED = 0x8574
export GL_ADD_SIGNED
const GL_INTERPOLATE = 0x8575
export GL_INTERPOLATE
const GL_SUBTRACT = 0x84E7
export GL_SUBTRACT
const GL_CONSTANT = 0x8576
export GL_CONSTANT
const GL_PRIMARY_COLOR = 0x8577
export GL_PRIMARY_COLOR
const GL_PREVIOUS = 0x8578
export GL_PREVIOUS
const GL_DOT3_RGB = 0x86AE
export GL_DOT3_RGB
const GL_DOT3_RGBA = 0x86AF
export GL_DOT3_RGBA
const GL_CLAMP_TO_BORDER = 0x812D
export GL_CLAMP_TO_BORDER
const GL_ARB_multitexture = 1
export GL_ARB_multitexture
const GL_TEXTURE0_ARB = 0x84C0
export GL_TEXTURE0_ARB
const GL_TEXTURE1_ARB = 0x84C1
export GL_TEXTURE1_ARB
const GL_TEXTURE2_ARB = 0x84C2
export GL_TEXTURE2_ARB
const GL_TEXTURE3_ARB = 0x84C3
export GL_TEXTURE3_ARB
const GL_TEXTURE4_ARB = 0x84C4
export GL_TEXTURE4_ARB
const GL_TEXTURE5_ARB = 0x84C5
export GL_TEXTURE5_ARB
const GL_TEXTURE6_ARB = 0x84C6
export GL_TEXTURE6_ARB
const GL_TEXTURE7_ARB = 0x84C7
export GL_TEXTURE7_ARB
const GL_TEXTURE8_ARB = 0x84C8
export GL_TEXTURE8_ARB
const GL_TEXTURE9_ARB = 0x84C9
export GL_TEXTURE9_ARB
const GL_TEXTURE10_ARB = 0x84CA
export GL_TEXTURE10_ARB
const GL_TEXTURE11_ARB = 0x84CB
export GL_TEXTURE11_ARB
const GL_TEXTURE12_ARB = 0x84CC
export GL_TEXTURE12_ARB
const GL_TEXTURE13_ARB = 0x84CD
export GL_TEXTURE13_ARB
const GL_TEXTURE14_ARB = 0x84CE
export GL_TEXTURE14_ARB
const GL_TEXTURE15_ARB = 0x84CF
export GL_TEXTURE15_ARB
const GL_TEXTURE16_ARB = 0x84D0
export GL_TEXTURE16_ARB
const GL_TEXTURE17_ARB = 0x84D1
export GL_TEXTURE17_ARB
const GL_TEXTURE18_ARB = 0x84D2
export GL_TEXTURE18_ARB
const GL_TEXTURE19_ARB = 0x84D3
export GL_TEXTURE19_ARB
const GL_TEXTURE20_ARB = 0x84D4
export GL_TEXTURE20_ARB
const GL_TEXTURE21_ARB = 0x84D5
export GL_TEXTURE21_ARB
const GL_TEXTURE22_ARB = 0x84D6
export GL_TEXTURE22_ARB
const GL_TEXTURE23_ARB = 0x84D7
export GL_TEXTURE23_ARB
const GL_TEXTURE24_ARB = 0x84D8
export GL_TEXTURE24_ARB
const GL_TEXTURE25_ARB = 0x84D9
export GL_TEXTURE25_ARB
const GL_TEXTURE26_ARB = 0x84DA
export GL_TEXTURE26_ARB
const GL_TEXTURE27_ARB = 0x84DB
export GL_TEXTURE27_ARB
const GL_TEXTURE28_ARB = 0x84DC
export GL_TEXTURE28_ARB
const GL_TEXTURE29_ARB = 0x84DD
export GL_TEXTURE29_ARB
const GL_TEXTURE30_ARB = 0x84DE
export GL_TEXTURE30_ARB
const GL_TEXTURE31_ARB = 0x84DF
export GL_TEXTURE31_ARB
const GL_ACTIVE_TEXTURE_ARB = 0x84E0
export GL_ACTIVE_TEXTURE_ARB
const GL_CLIENT_ACTIVE_TEXTURE_ARB = 0x84E1
export GL_CLIENT_ACTIVE_TEXTURE_ARB
const GL_MAX_TEXTURE_UNITS_ARB = 0x84E2
export GL_MAX_TEXTURE_UNITS_ARB
const GL_MESA_shader_debug = 1
export GL_MESA_shader_debug
const GL_DEBUG_OBJECT_MESA = 0x8759
export GL_DEBUG_OBJECT_MESA
const GL_DEBUG_PRINT_MESA = 0x875A
export GL_DEBUG_PRINT_MESA
const GL_DEBUG_ASSERT_MESA = 0x875B
export GL_DEBUG_ASSERT_MESA
const GL_MESA_packed_depth_stencil = 1
export GL_MESA_packed_depth_stencil
const GL_DEPTH_STENCIL_MESA = 0x8750
export GL_DEPTH_STENCIL_MESA
const GL_UNSIGNED_INT_24_8_MESA = 0x8751
export GL_UNSIGNED_INT_24_8_MESA
const GL_UNSIGNED_INT_8_24_REV_MESA = 0x8752
export GL_UNSIGNED_INT_8_24_REV_MESA
const GL_UNSIGNED_SHORT_15_1_MESA = 0x8753
export GL_UNSIGNED_SHORT_15_1_MESA
const GL_UNSIGNED_SHORT_1_15_REV_MESA = 0x8754
export GL_UNSIGNED_SHORT_1_15_REV_MESA
const GL_MESA_program_debug = 1
export GL_MESA_program_debug
const GL_FRAGMENT_PROGRAM_POSITION_MESA = 0x8bb0
export GL_FRAGMENT_PROGRAM_POSITION_MESA
const GL_FRAGMENT_PROGRAM_CALLBACK_MESA = 0x8bb1
export GL_FRAGMENT_PROGRAM_CALLBACK_MESA
const GL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA = 0x8bb2
export GL_FRAGMENT_PROGRAM_CALLBACK_FUNC_MESA
const GL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA = 0x8bb3
export GL_FRAGMENT_PROGRAM_CALLBACK_DATA_MESA
const GL_VERTEX_PROGRAM_POSITION_MESA = 0x8bb4
export GL_VERTEX_PROGRAM_POSITION_MESA
const GL_VERTEX_PROGRAM_CALLBACK_MESA = 0x8bb5
export GL_VERTEX_PROGRAM_CALLBACK_MESA
const GL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA = 0x8bb6
export GL_VERTEX_PROGRAM_CALLBACK_FUNC_MESA
const GL_VERTEX_PROGRAM_CALLBACK_DATA_MESA = 0x8bb7
export GL_VERTEX_PROGRAM_CALLBACK_DATA_MESA
const GL_MESA_texture_array = 1
export GL_MESA_texture_array
const GL_TEXTURE_1D_ARRAY_EXT = 0x8C18
export GL_TEXTURE_1D_ARRAY_EXT
const GL_PROXY_TEXTURE_1D_ARRAY_EXT = 0x8C19
export GL_PROXY_TEXTURE_1D_ARRAY_EXT
const GL_TEXTURE_2D_ARRAY_EXT = 0x8C1A
export GL_TEXTURE_2D_ARRAY_EXT
const GL_PROXY_TEXTURE_2D_ARRAY_EXT = 0x8C1B
export GL_PROXY_TEXTURE_2D_ARRAY_EXT
const GL_TEXTURE_BINDING_1D_ARRAY_EXT = 0x8C1C
export GL_TEXTURE_BINDING_1D_ARRAY_EXT
const GL_TEXTURE_BINDING_2D_ARRAY_EXT = 0x8C1D
export GL_TEXTURE_BINDING_2D_ARRAY_EXT
const GL_MAX_ARRAY_TEXTURE_LAYERS_EXT = 0x88FF
export GL_MAX_ARRAY_TEXTURE_LAYERS_EXT
const GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT = 0x8CD4
export GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT
const GL_ATI_blend_equation_separate = 1
export GL_ATI_blend_equation_separate
const GL_ALPHA_BLEND_EQUATION_ATI = 0x883D
export GL_ALPHA_BLEND_EQUATION_ATI
const GL_OES_EGL_image = 1
export GL_OES_EGL_image

end # module OpenGL
